import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { editorRouter } from '../server/video-editor/routes.mjs';
import { signToken } from '../server/video-editor/assets.mjs';
import {
  verifySession,
  readSessionCookie,
  issueSession,
  isAllowedOrigin,
} from '../server/auth.mjs';

test('editor endpoints require a session and same-origin writes; planner handoff is idempotent and retains the exported video', async () => {
  const previousSecret = process.env.SESSION_SECRET,
    previousCloud = process.env.CLOUDINARY_CLOUD_NAME;
  process.env.SESSION_SECRET = 'test-only-routes-secret';
  process.env.CLOUDINARY_CLOUD_NAME = 'editor-route-tests';
  const posts = new Map(),
    app = express();
  let insertions = 0;
  app.use(express.json());
  app.use('/api', (req, res, next) => {
    if (!verifySession(readSessionCookie(req), process.env.SESSION_SECRET))
      return res.sendStatus(401);
    if (req.method !== 'GET' && !isAllowedOrigin(req)) return res.sendStatus(403);
    next();
  });
  app.use(
    '/api/video-editor',
    editorRouter({
      loadPost: async (id) => posts.get(id),
      insertPost: async (p) => {
        insertions++;
        posts.set(p.id, p);
        return p;
      },
    }),
  );
  const server = app.listen(0, '127.0.0.1');
  await new Promise((resolve) => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`,
    cookie = `silent_forward_session=${issueSession(process.env.SESSION_SECRET)}`;
  const headers = { 'Content-Type': 'application/json', Cookie: cookie, Origin: base };
  try {
    assert.equal((await fetch(base + '/api/video-editor/capabilities')).status, 401);
    assert.equal(
      (
        await fetch(base + '/api/video-editor/upload-ticket', {
          method: 'POST',
          headers: { ...headers, Origin: 'https://unrelated.example' },
          body: JSON.stringify({ kind: 'video' }),
        })
      ).status,
      403,
    );
    assert.equal(
      (
        await fetch(base + '/api/video-editor/export', {
          method: 'POST',
          headers,
          body: JSON.stringify({ project: {} }),
        })
      ).status,
      400,
    );
    const id = 'b1234567-1234-1234-1234-123456789abc',
      url = `https://res.cloudinary.com/editor-route-tests/video/upload/v123/silent-forward/editor-export/${id}.mp4`;
    const token = signToken({
      purpose: 'export',
      id,
      cloud: true,
      url,
      width: 1080,
      height: 1920,
      duration: 15,
    });
    const body = JSON.stringify({
      token,
      name: 'Edited Reel',
      caption: 'My finished edit',
      scheduledFor: new Date(Date.now() + 3600000).toISOString(),
    });
    const first = await fetch(base + '/api/video-editor/planner', {
      method: 'POST',
      headers,
      body,
    });
    assert.equal(first.status, 201);
    const post = await first.json();
    assert.equal(post.mediaUrl, url);
    assert.equal(post.design.editorMedia.url, url);
    assert.equal(post.status, 'scheduled');
    assert.equal(post.autoGenerated, false);
    assert.equal(post.caption, 'My finished edit');
    const repeated = await fetch(base + '/api/video-editor/planner', {
      method: 'POST',
      headers,
      body,
    });
    assert.equal(repeated.status, 200);
    assert.equal(insertions, 1);
    const landscape = signToken({
      purpose: 'export',
      id,
      cloud: true,
      url,
      width: 1920,
      height: 1080,
      duration: 15,
    });
    assert.equal(
      (
        await fetch(base + '/api/video-editor/planner', {
          method: 'POST',
          headers,
          body: JSON.stringify({ ...JSON.parse(body), token: landscape }),
        })
      ).status,
      400,
    );
    assert.equal(
      (
        await fetch(base + '/api/video-editor/planner', {
          method: 'POST',
          headers,
          body: JSON.stringify({ ...JSON.parse(body), token: token + 'x' }),
        })
      ).status,
      400,
    );
  } finally {
    await new Promise((resolve) => server.close(resolve));
    if (previousSecret === undefined) delete process.env.SESSION_SECRET;
    else process.env.SESSION_SECRET = previousSecret;
    if (previousCloud === undefined) delete process.env.CLOUDINARY_CLOUD_NAME;
    else process.env.CLOUDINARY_CLOUD_NAME = previousCloud;
  }
});
