import type { CSSProperties } from 'react';
import {
  ArrowLeft,
  BarChart3,
  CalendarDays,
  Check,
  ChevronRight,
  CircleHelp,
  Clapperboard,
  Copy,
  Ellipsis,
  Eye,
  FolderOpen,
  ImageIcon,
  Info,
  LayoutDashboard,
  LayoutGrid,
  List,
  LockKeyhole,
  LogOut,
  Magnet,
  Maximize2,
  Menu,
  Minus,
  Moon,
  Music2,
  PanelLeft,
  Pause,
  Play,
  Plus,
  RotateCcw,
  Save,
  Scissors,
  Search,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  Type,
  Undo2,
  Redo2,
  Upload,
  Volume2,
  VolumeX,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  calendar: CalendarDays,
  chart: BarChart3,
  settings: SlidersHorizontal,
  bolt: Zap,
  menu: Menu,
  sidebar: PanelLeft,
  logout: LogOut,
  list: List,
  search: Search,
  info: Info,
  more: Ellipsis,
  play: Play,
  pause: Pause,
  import: Upload,
  export: Upload,
  back: ArrowLeft,
  undo: Undo2,
  redo: Redo2,
  split: Scissors,
  copy: Copy,
  trash: Trash2,
  video: Clapperboard,
  audio: Music2,
  text: Type,
  image: ImageIcon,
  effects: Sparkles,
  templates: LayoutGrid,
  volume: Volume2,
  mute: VolumeX,
  fullscreen: Maximize2,
  replay: RotateCcw,
  previous: SkipBack,
  next: SkipForward,
  plus: Plus,
  minus: Minus,
  close: X,
  save: Save,
  eye: Eye,
  lock: LockKeyhole,
  magnet: Magnet,
  chevron: ChevronRight,
  check: Check,
  folder: FolderOpen,
  help: CircleHelp,
  sun: Sun,
  moon: Moon,
};

export function Icon({
  name,
  size = 18,
  style,
}: {
  name: string;
  size?: number;
  style?: CSSProperties;
}) {
  const Component = icons[name] ?? CircleHelp;
  return <Component size={size} strokeWidth={1.8} aria-hidden="true" style={style} />;
}
