import { supabase } from './supabase.mjs'

function postFromDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption,
    accent: post.accent,
    format: post.format,
    status: post.status,
    scheduledFor: post.scheduled_for,
    createdAt: post.created_at,
    autoGenerated: post.auto_generated,
    mediaUrl: post.media_url,
    instagramMediaId: post.instagram_media_id,
    publishedAt: post.published_at,
    error: post.error,
  }
}

function postToDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption ?? '',
    accent: post.accent ?? '#d9ff3f',
    format: post.format,
    status: post.status,
    scheduled_for: post.scheduledFor,
    created_at: post.createdAt,
    auto_generated: post.autoGenerated ?? false,
    media_url: post.mediaUrl ?? null,
    instagram_media_id: post.instagramMediaId ?? null,
    published_at: post.publishedAt ?? null,
    error: post.error ?? '',
  }
}

export async function loadDatabase() {
  const { data: settings, error: settingsError } = await supabase
    .from('app_settings')
    .select('*')
    .eq('id', 1)
    .single()

  if (settingsError) throw settingsError

  const { data: posts, error: postsError } = await supabase
    .from('posts')
    .select('*')
    .order('scheduled_for', { ascending: true })

  if (postsError) throw postsError

  return {
    schemaVersion: settings.schema_version,
    settings: {
      autopilot: settings.autopilot,
      postTime: settings.post_time.slice(0, 5),
      reelTime: settings.reel_time.slice(0, 5),
      timezone: settings.timezone,
      queueDays: settings.queue_days,
    },
    posts: posts.map(postFromDatabase),
    quoteCursor: settings.quote_cursor,
  }
}

export async function saveDatabase(database) {
  const { error: settingsError } = await supabase
    .from('app_settings')
    .update({
      schema_version: database.schemaVersion,
      autopilot: database.settings.autopilot,
      post_time: database.settings.postTime,
      reel_time: database.settings.reelTime,
      timezone: database.settings.timezone,
      queue_days: database.settings.queueDays,
      quote_cursor: database.quoteCursor,
      updated_at: new Date().toISOString(),
    })
    .eq('id', 1)

  if (settingsError) throw settingsError

  const posts = database.posts.map(postToDatabase)

  if (posts.length > 0) {
    const { error: postsError } = await supabase
      .from('posts')
      .upsert(posts)

    if (postsError) throw postsError
  }

  const ids = database.posts.map((post) => post.id)

  let deleteQuery = supabase.from('posts').delete()

  if (ids.length > 0) {
    deleteQuery = deleteQuery.not('id', 'in', `(${ids.join(',')})`)
  } else {
    deleteQuery = deleteQuery.neq('id', '00000000-0000-0000-0000-000000000000')
  }

  const { error: deleteError } = await deleteQuery

  if (deleteError) throw deleteError
}