import { supabase } from './supabase.mjs'
import { normalizeDesign } from './design.mjs'

function postFromDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption,
    accent: post.accent,
    format: post.format,
    status: post.status,
    scheduledFor: post.scheduled_for,
    createdAt: post.created_at,
    autoGenerated: post.auto_generated,
    design: normalizeDesign(post.design, post.format),
    mediaUrl: post.media_url,
    instagramMediaId: post.instagram_media_id,
    publishedAt: post.published_at,
    error: post.error,
  }
}

function postToDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption ?? '',
    accent: post.accent ?? '#d9ff3f',
    format: post.format,
    status: post.status,
    scheduled_for: post.scheduledFor,
    created_at: post.createdAt,
    auto_generated: post.autoGenerated ?? false,
    design: normalizeDesign(post.design, post.format),
    media_url: post.mediaUrl ?? null,
    instagram_media_id: post.instagramMediaId ?? null,
    published_at: post.publishedAt ?? null,
    error: post.error ?? '',
  }
}

function settingsFromDatabase(settings) {
  return {
    schemaVersion: settings.schema_version,
    autopilot: settings.autopilot,
    postTime: settings.post_time.slice(0, 5),
    reelTime: settings.reel_time.slice(0, 5),
    timezone: settings.timezone,
    queueDays: settings.queue_days,
    quoteCursor: settings.quote_cursor,
  }
}

export async function loadSettings() {
  const { data, error } = await supabase.from('app_settings').select('*').eq('id', 1).single()
  if (error) throw error
  return settingsFromDatabase(data)
}

export async function loadDatabase() {
  const [settings, postsResult] = await Promise.all([
    loadSettings(),
    supabase.from('posts').select('*').order('scheduled_for', { ascending: true }),
  ])
  if (postsResult.error) throw postsResult.error
  return {
    schemaVersion: settings.schemaVersion,
    settings: {
      autopilot: settings.autopilot,
      postTime: settings.postTime,
      reelTime: settings.reelTime,
      timezone: settings.timezone,
      queueDays: settings.queueDays,
    },
    posts: postsResult.data.map(postFromDatabase),
    quoteCursor: settings.quoteCursor,
  }
}

export async function updateSettings(settings, quoteCursor) {
  const values = {
    schema_version: settings.schemaVersion ?? 3,
    autopilot: settings.autopilot,
    post_time: settings.postTime,
    reel_time: settings.reelTime,
    timezone: settings.timezone,
    queue_days: settings.queueDays,
    updated_at: new Date().toISOString(),
  }
  if (quoteCursor !== undefined) values.quote_cursor = quoteCursor
  const { data, error } = await supabase.from('app_settings').update(values).eq('id', 1).select('*').single()
  if (error) throw error
  return settingsFromDatabase(data)
}

export async function insertPosts(posts) {
  if (!posts.length) return []
  const { data, error } = await supabase.from('posts').insert(posts.map(postToDatabase)).select('*')
  if (error) throw error
  return data.map(postFromDatabase)
}

export async function insertPost(post) {
  const [created] = await insertPosts([post])
  return created
}

export async function loadPost(id) {
  const { data, error } = await supabase.from('posts').select('*').eq('id', id).maybeSingle()
  if (error) throw error
  return data ? postFromDatabase(data) : null
}

export async function savePost(post) {
  const { data, error } = await supabase.from('posts').upsert(postToDatabase(post)).select('*').single()
  if (error) throw error
  return postFromDatabase(data)
}

export async function claimPostForPublishing(id) {
  const { data, error } = await supabase
    .from('posts')
    .update({ status: 'publishing', error: '' })
    .eq('id', id)
    .in('status', ['scheduled', 'failed'])
    .select('*')
    .maybeSingle()
  if (error) throw error
  return data ? postFromDatabase(data) : null
}

export async function deletePost(id) {
  const { error } = await supabase.from('posts').delete().eq('id', id)
  if (error) throw error
}
