import { supabase } from './supabase.mjs'
import { normalizeDesign } from './design.mjs'
import { withRemoteRetries } from './retry.mjs'

const retryOptions = {
  attempts: 5,
  baseDelayMs: 2_000,
  onRetry: ({ attempt, delayMs, error }) => {
    const message = error instanceof Error ? error.message : String(error?.message ?? error)
    console.warn(`[database] ${message}. Reîncercarea ${attempt + 1}/5 începe în ${Math.round(delayMs / 1000)}s.`)
  },
}

async function databaseRequest(label, operation) {
  return withRemoteRetries(async () => {
    const result = await operation()
    if (result.error) throw result.error
    return result.data
  }, {
    ...retryOptions,
    onRetry: (state) => {
      console.warn(`[database:${label}] Cererea remote a eșuat temporar.`)
      retryOptions.onRetry(state)
    },
  })
}

function postFromDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption,
    accent: post.accent,
    format: post.format,
    status: post.status,
    scheduledFor: post.scheduled_for,
    createdAt: post.created_at,
    autoGenerated: post.auto_generated,
    design: normalizeDesign(post.design, post.format),
    mediaUrl: post.media_url,
    instagramMediaId: post.instagram_media_id,
    publishedAt: post.published_at,
    error: post.error,
    retryCount: post.retry_count ?? 0,
    nextAttemptAt: post.next_attempt_at ?? null,
  }
}

function postToDatabase(post) {
  return {
    id: post.id,
    quote: post.quote,
    caption: post.caption ?? '',
    accent: post.accent ?? '#d9ff3f',
    format: post.format,
    status: post.status,
    scheduled_for: post.scheduledFor,
    created_at: post.createdAt,
    auto_generated: post.autoGenerated ?? false,
    design: normalizeDesign(post.design, post.format),
    media_url: post.mediaUrl ?? null,
    instagram_media_id: post.instagramMediaId ?? null,
    published_at: post.publishedAt ?? null,
    error: post.error ?? '',
    retry_count: post.retryCount ?? 0,
    next_attempt_at: post.nextAttemptAt ?? null,
  }
}

function settingsFromDatabase(settings) {
  return {
    schemaVersion: settings.schema_version,
    autopilot: settings.autopilot,
    postTime: settings.post_time.slice(0, 5),
    reelTime: settings.reel_time.slice(0, 5),
    timezone: settings.timezone,
    queueDays: settings.queue_days,
    quoteCursor: settings.quote_cursor,
  }
}

function workerStateFromDatabase(state) {
  if (!state) return null
  return {
    runId: state.run_id,
    source: state.source,
    status: state.status,
    startedAt: state.started_at,
    finishedAt: state.finished_at,
    lastSuccessAt: state.last_success_at,
    lastError: state.last_error,
    lastResult: state.last_result ?? {},
  }
}

export async function loadSettings() {
  const data = await databaseRequest('settings', () => supabase.from('app_settings').select('*').eq('id', 1).single())
  return settingsFromDatabase(data)
}

export async function loadDatabase() {
  const [settings, postsResult] = await Promise.all([
    loadSettings(),
    databaseRequest('posts', () => supabase.from('posts').select('*').order('scheduled_for', { ascending: true })),
  ])
  return {
    schemaVersion: settings.schemaVersion,
    settings: {
      autopilot: settings.autopilot,
      postTime: settings.postTime,
      reelTime: settings.reelTime,
      timezone: settings.timezone,
      queueDays: settings.queueDays,
    },
    posts: postsResult.map(postFromDatabase),
    quoteCursor: settings.quoteCursor,
  }
}

export async function loadWorkerState() {
  const data = await databaseRequest('worker-state', () => supabase.from('worker_state').select('*').eq('id', 1).maybeSingle())
  return workerStateFromDatabase(data)
}

export async function claimWorkerLease(name, owner, leaseSeconds = 240) {
  const data = await databaseRequest('claim-worker-lease', () => supabase.rpc('claim_worker_lease', {
    p_name: name,
    p_owner: owner,
    p_lease_seconds: leaseSeconds,
  }))
  return Boolean(data)
}

export async function releaseWorkerLease(name, owner) {
  await databaseRequest('release-worker-lease', () => supabase.rpc('release_worker_lease', {
    p_name: name,
    p_owner: owner,
  }))
}

export async function beginWorkerRun(runId, source) {
  const now = new Date().toISOString()
  const data = await databaseRequest('begin-worker-run', () => supabase.from('worker_state').upsert({
    id: 1,
    run_id: runId,
    source: String(source || 'unknown').slice(0, 80),
    status: 'running',
    started_at: now,
    finished_at: null,
    updated_at: now,
  }).select('*').single())
  return workerStateFromDatabase(data)
}

export async function finishWorkerRun(runId, values) {
  const now = new Date().toISOString()
  const update = {
    status: values.status,
    finished_at: now,
    last_error: String(values.error || '').slice(0, 2000),
    last_result: values.result ?? {},
    updated_at: now,
  }
  if (values.status === 'succeeded') update.last_success_at = now
  const data = await databaseRequest('finish-worker-run', () => supabase.from('worker_state')
    .update(update)
    .eq('id', 1)
    .eq('run_id', runId)
    .select('*')
    .maybeSingle())
  return workerStateFromDatabase(data)
}

export async function updateSettings(settings, quoteCursor) {
  const values = {
    schema_version: settings.schemaVersion ?? 3,
    autopilot: settings.autopilot,
    post_time: settings.postTime,
    reel_time: settings.reelTime,
    timezone: settings.timezone,
    queue_days: settings.queueDays,
    updated_at: new Date().toISOString(),
  }
  if (quoteCursor !== undefined) values.quote_cursor = quoteCursor
  const data = await databaseRequest('update-settings', () => supabase.from('app_settings').update(values).eq('id', 1).select('*').single())
  return settingsFromDatabase(data)
}

export async function insertPosts(posts) {
  if (!posts.length) return []
  const data = await databaseRequest('insert-posts', () => supabase.from('posts').insert(posts.map(postToDatabase)).select('*'))
  return data.map(postFromDatabase)
}

export async function insertPost(post) {
  const [created] = await insertPosts([post])
  return created
}

export async function loadPost(id) {
  const data = await databaseRequest('load-post', () => supabase.from('posts').select('*').eq('id', id).maybeSingle())
  return data ? postFromDatabase(data) : null
}

export async function savePost(post) {
  const data = await databaseRequest('save-post', () => supabase.from('posts').upsert(postToDatabase(post)).select('*').single())
  return postFromDatabase(data)
}

export async function claimPostForPublishing(id) {
  const leaseExpiresAt = new Date(Date.now() + 15 * 60_000).toISOString()
  const data = await databaseRequest('claim-post', () => supabase
    .from('posts')
    .update({ status: 'publishing', error: '', next_attempt_at: leaseExpiresAt })
    .eq('id', id)
    .in('status', ['scheduled', 'failed'])
    .select('*')
    .maybeSingle())
  return data ? postFromDatabase(data) : null
}

export async function releaseExpiredClaims(now = new Date()) {
  const data = await databaseRequest('release-expired-claims', () => supabase
    .from('posts')
    .update({ status: 'failed', error: 'Publicarea a fost întreruptă după pornire. Verifică Instagram înainte de reîncercare pentru a evita un duplicat.', next_attempt_at: null })
    .eq('status', 'publishing')
    .lt('next_attempt_at', now.toISOString())
    .select('*'))
  return data.map(postFromDatabase)
}

export async function deletePost(id) {
  await databaseRequest('delete-post', () => supabase.from('posts').delete().eq('id', id))
}
