import { randomUUID } from 'node:crypto';
import { unlink } from 'node:fs/promises';
import { REEL_VERSION, planReel, chooseQuote, qualityIssue } from './reel-plan.mjs';
import { growthDesignFor } from './growth-engine.mjs';
import { captionFor } from './content-plan.mjs';

export const eligibleForRefresh = (post, now = Date.now()) =>
  post.format === 'reel' &&
  post.status === 'scheduled' &&
  !post.design?.editorMedia &&
  new Date(post.scheduledFor).getTime() > now;

// Pure orchestration with injected storage so concurrency/failures can be tested without production access.
export async function refreshScheduledReel(
  id,
  { snapshot, replace, generate, upload, directory, quotes = [], history = [] },
) {
  const before = await snapshot(id);
  if (!before || !eligibleForRefresh(before.post)) return { id, status: 'skipped' };
  const post = before.post;
  const cursor = Math.max(
    0,
    history.findIndex((item) => item.id === id),
  );
  const previous = history.slice(0, cursor);
  let quote = post.quote;
  if (post.autoGenerated && qualityIssue(quote))
    quote = chooseQuote(quotes, history.length, history);
  const design = post.autoGenerated
    ? {
        ...post.design,
        ...growthDesignFor(quote, 'reel', cursor, previous),
        story: post.design.story,
      }
    : { ...post.design };
  design.duration = planReel(quote, design).duration;
  design.reelVersion = REEL_VERSION;
  const updated = {
    ...post,
    quote,
    design,
    caption: post.autoGenerated ? captionFor(quote, 'reel', cursor, design.growth) : post.caption,
  };
  const renderPost = { ...updated, id: `${post.id}-refresh-${randomUUID()}` };
  let file;
  try {
    file = await generate(renderPost, directory); // renderer validates the complete video before returning
    updated.mediaUrl = await upload(file, renderPost);
    const saved = await replace(before, updated); // atomic compare-and-swap; never restores a stale scheduled status
    return { id, status: saved ? 'refreshed' : 'conflict' };
  } finally {
    if (file) await unlink(file).catch(() => {});
  }
}
