import { Icon } from './video-editor/Icon';
import { FloatingMenu } from './FloatingMenu';
import { ThemeToggle } from './Theme';
import { SoundscapePreview } from './SoundscapePreview';
import { planReel } from '../server/reel-plan.mjs';
import { FormEvent, Suspense, lazy, useEffect, useMemo, useRef, useState } from 'react';

const VideoEditor = lazy(() => import('./video-editor/VideoEditor'));

type Format = 'post' | 'reel';
type Status = 'scheduled' | 'publishing' | 'published' | 'failed';
type Page =
  | 'overview'
  | 'planner'
  | 'studio'
  | 'library'
  | 'analytics'
  | 'settings'
  | 'calendar'
  | 'automation';
type StoryState = {
  status: 'pending' | 'publishing' | 'published' | 'failed';
  mediaUrl?: string;
  instagramMediaId?: string;
  publishedAt?: string;
  error?: string;
  retryCount?: number;
  nextAttemptAt?: string;
};
type GrowthState = {
  version: string;
  recipe: string;
  pillar: string;
  hook: string;
  cta: string;
  objective: 'share' | 'save' | 'retain' | 'follow';
  shareabilityScore: number;
  selection: 'explore' | 'exploit';
};
type PerformanceState = {
  checkedAt: string;
  views: number;
  reach: number;
  likes: number;
  comments: number;
  shares: number;
  saved: number;
  averageWatchTimeMs: number;
  score: number;
  confidence: number;
};
type Design = {
  editorMedia?: { url: string; width: number; height: number; duration: number } | null;
  template: string;
  font: string;
  textPosition: string;
  textAlign: string;
  fontSize: number;
  animation: string;
  duration: number;
  music: string;
  musicVolume: number;
  textCase: string;
  letterSpacing: number;
  lineHeight: number;
  overlayOpacity: number;
  story?: StoryState | null;
  growth?: GrowthState | null;
  performance?: PerformanceState | null;
};
type Post = {
  id: string;
  quote: string;
  caption: string;
  accent: string;
  format: Format;
  status: Status;
  scheduledFor: string;
  publishedAt?: string;
  design: Design;
  mediaUrl?: string;
  instagramMediaId?: string;
  error?: string;
  autoGenerated?: boolean;
};
type Dashboard = {
  account: { connected: boolean; username: string; accountType: string };
  branding: { name: string; username: string };
  publishingReady: boolean;
  automation: {
    configured: boolean;
    lastRun: null | { status: string; lastSuccessAt?: string; lastError?: string };
  };
  posts: Post[];
  settings: {
    autopilot: boolean;
    postTime: string;
    reelTime: string;
    reelTimes: string[];
    postWeekdays: number[];
    timezone: string;
    queueDays: number;
  };
  contentPlan: {
    reelsPerDay: number;
    reelTimes: string[];
    postsPerWeek: number;
    postWeekdays: number[];
    storyAfterEveryPublication: boolean;
    growthStrategy: string;
  };
  stats: {
    scheduled: number;
    published: number;
    failed: number;
    storiesPublished: number;
    storiesFailed: number;
    insightsCollected: number;
    averageGrowthScore: number;
  };
  designOptions: {
    templates: string[];
    fonts: string[];
    textPositions: string[];
    textAlignments: string[];
    textCases: string[];
    animations: string[];
    music: string[];
  };
};
type Draft = {
  quote: string;
  caption: string;
  accent: string;
  format: Format;
  scheduledFor: string;
  design: Design;
};

const accents = [
  '#d9ff3f',
  '#ff5c35',
  '#62e6ff',
  '#d8a7ff',
  '#ffcf5c',
  '#71f6a5',
  '#ff7eb6',
  '#ffffff',
];
const fallbackOptions = {
  templates: [
    'midnight',
    'aurora',
    'ember',
    'ocean',
    'monochrome',
    'paper',
    'forest',
    'dusk',
    'sandstone',
    'neon',
    'obsidian',
    'meadow',
    'cinematic',
    'concrete',
    'afterglow',
    'signal',
  ],
  fonts: ['sans', 'serif', 'mono'],
  textPositions: ['top', 'center', 'bottom'],
  textAlignments: ['left', 'center', 'right'],
  textCases: ['normal', 'uppercase'],
  animations: ['drift', 'zoom', 'slide', 'pulse', 'float', 'pan', 'breathe', 'static'],
  music: [
    'ambient',
    'deep',
    'focus',
    'pulse',
    'serenity',
    'nostalgia',
    'horizon',
    'starlight',
    'snowfall',
    'silent',
  ],
};
const defaultDesign: Design = {
  template: 'midnight',
  font: 'sans',
  textPosition: 'center',
  textAlign: 'left',
  fontSize: 82,
  animation: 'drift',
  duration: 8,
  music: 'serenity',
  musicVolume: 48,
  textCase: 'normal',
  letterSpacing: 0,
  lineHeight: 112,
  overlayOpacity: 10,
};
const initialDashboard: Dashboard = {
  account: { connected: false, username: 'silentforward', accountType: 'BUSINESS' },
  branding: { name: 'Silent Forward', username: 'silentforward' },
  publishingReady: false,
  automation: { configured: false, lastRun: null },
  posts: [],
  settings: {
    autopilot: true,
    postTime: '11:00',
    reelTime: '15:30',
    reelTimes: ['09:00', '15:30', '21:00'],
    postWeekdays: [2, 6],
    timezone: 'Europe/Chisinau',
    queueDays: 14,
  },
  contentPlan: {
    reelsPerDay: 3,
    reelTimes: ['09:00', '15:30', '21:00'],
    postsPerWeek: 2,
    postWeekdays: [2, 6],
    storyAfterEveryPublication: true,
    growthStrategy: '2026.1',
  },
  stats: {
    scheduled: 0,
    published: 0,
    failed: 0,
    storiesPublished: 0,
    storiesFailed: 0,
    insightsCollected: 0,
    averageGrowthScore: 0,
  },
  designOptions: fallbackOptions,
};
const pageMeta: Record<
  Page,
  { label: string; eyebrow: string; title: string; description: string }
> = {
  overview: {
    label: 'Overview',
    eyebrow: 'Workspace',
    title: 'O privire de ansamblu',
    description: 'Conținutul tău, în ritmul potrivit.',
  },
  planner: {
    label: 'Content',
    eyebrow: 'Workspace',
    title: 'Conținut',
    description: 'Revizuiește, organizează și publică dintr-un singur loc.',
  },
  studio: {
    label: 'Create',
    eyebrow: 'Creative studio',
    title: 'Creează ceva nou',
    description: 'De la idee la următoarea postare.',
  },
  calendar: {
    label: 'Calendar',
    eyebrow: 'Publishing',
    title: 'Calendar editorial',
    description: 'Următoarele zile, deja organizate. Orele sunt afișate în fusul tău local.',
  },
  library: {
    label: 'Assets',
    eyebrow: 'Creative library',
    title: 'Biblioteca ta',
    description: 'Conținut, sunete și stiluri pe care le poți reutiliza.',
  },
  analytics: {
    label: 'Analytics',
    eyebrow: 'Insights',
    title: 'Vezi ce funcționează',
    description: 'Rezultatele reale ale conținutului publicat.',
  },
  automation: {
    label: 'Automation',
    eyebrow: 'Publishing',
    title: 'Automatizare',
    description: 'Un ritm constant. Controlul rămâne la tine.',
  },
  settings: {
    label: 'Settings',
    eyebrow: 'Workspace',
    title: 'Setări și conexiuni',
    description: 'Contul tău și serviciile care țin lucrurile în mișcare.',
  },
};
function currentPage(): Page {
  const value = location.hash.slice(1);
  return Object.prototype.hasOwnProperty.call(pageMeta, value) ? (value as Page) : 'overview';
}
function useQueryPreference(key: string, fallback: string) {
  const [value, setValue] = useState(
    () => new URLSearchParams(location.search).get(key) || fallback,
  );
  useEffect(() => {
    const url = new URL(location.href);
    if (value === fallback) url.searchParams.delete(key);
    else url.searchParams.set(key, value);
    history.replaceState(null, '', url);
  }, [key, value, fallback]);
  return [value, setValue] as const;
}
const statusLabels: Record<Status, string> = {
  scheduled: 'Programat',
  published: 'Publicat',
  publishing: 'Se publică',
  failed: 'Eroare',
};
function StatusBadge({ status }: { status: Status }) {
  return (
    <span className={`status ${status}`}>
      <i />
      {statusLabels[status]}
    </span>
  );
}
function EmptyState({
  title,
  description,
  action,
}: {
  title: string;
  description: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="empty-state">
      <span className="empty-symbol">
        <Icon name="folder" size={24} />
      </span>
      <h3>{title}</h3>
      <p>{description}</p>
      {action}
    </div>
  );
}
function DashboardSkeleton() {
  return (
    <div className="dashboard-skeleton" aria-label="Se încarcă dashboard-ul" role="status">
      <div className="skeleton-metrics">
        {[1, 2, 3, 4].map((i) => (
          <div key={i} />
        ))}
      </div>
      <div className="skeleton-content">
        <div />
        <div />
      </div>
    </div>
  );
}
const weekdays: Record<number, string> = {
  1: 'Luni',
  2: 'Marți',
  3: 'Miercuri',
  4: 'Joi',
  5: 'Vineri',
  6: 'Sâmbătă',
  7: 'Duminică',
};

function localInput(date = new Date(Date.now() + 3_600_000)) {
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
}
function initialDraft(): Draft {
  return {
    quote: 'Discipline gets quiet before results get loud.',
    caption:
      'A reminder for the work nobody sees.\n\nQuiet work. Visible results.\n\n#motivation #discipline #mindset #consistency',
    accent: accents[0],
    format: 'reel',
    scheduledFor: localInput(),
    design: { ...defaultDesign },
  };
}
function isoToLocalInput(value: string) {
  return localInput(new Date(value));
}
function formatDate(value?: string, options: Intl.DateTimeFormatOptions = {}) {
  if (!value) return '—';
  return new Intl.DateTimeFormat('ro-RO', {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
    ...options,
  }).format(new Date(value));
}
function dateKey(value: string) {
  return new Intl.DateTimeFormat('sv-SE', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(new Date(value));
}
function shortDay(value: string) {
  return new Intl.DateTimeFormat('ro-RO', {
    weekday: 'short',
    day: '2-digit',
    month: 'short',
  }).format(new Date(value));
}
async function responseJson(response: Response) {
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || 'Cererea nu a putut fi finalizată.');
  return result;
}

function Login({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const local = ['localhost', '127.0.0.1'].includes(window.location.hostname);
  async function submit(event: FormEvent) {
    event.preventDefault();
    setLoading(true);
    setError('');
    try {
      await responseJson(
        await fetch('/api/auth/login', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ password }),
        }),
      );
      onAuthenticated();
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Autentificarea a eșuat.');
    } finally {
      setLoading(false);
    }
  }
  return (
    <main className="login-page">
      <section className="login-story">
        <div className="brand">
          <span>SF</span>
          <div>
            <strong>SilentForward</strong>
            <small>CONTENT STUDIO</small>
          </div>
        </div>
        <div className="login-pitch">
          <p className="eyebrow">MAI PUȚINĂ RUTINĂ. MAI MULTĂ CREAȚIE.</p>
          <h1>
            Conținutul merge înainte.
            <br />
            <em>Tu alegi direcția.</em>
          </h1>
          <p>
            Generează, programează și urmărește rezultatele. Un singur spațiu pentru ideile tale.
          </p>
          <div className="login-flow">
            <span>
              <Icon name="effects" /> Creează
            </span>
            <Icon name="chevron" size={14} />
            <span>
              <Icon name="calendar" /> Programează
            </span>
            <Icon name="chevron" size={14} />
            <span>
              <Icon name="chart" /> Analizează
            </span>
          </div>
        </div>
        <small className="login-signature">SilentForward / Quiet ambition.</small>
      </section>
      <section className="login-form-side">
        <ThemeToggle className="login-theme-toggle" />
        <div className="login-card">
          <h2>Bine ai revenit.</h2>
          <p className="login-copy">Autentifică-te pentru a continua.</p>
          <form onSubmit={submit}>
            <label>
              Parolă
              <input
                type="password"
                placeholder="Introdu parola contului"
                autoComplete="current-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                autoFocus
                required
              />
            </label>
            <button className="primary" disabled={loading}>
              {loading ? 'Se verifică…' : 'Intră în studio'}
              <Icon name="chevron" size={16} />
            </button>
            {error && (
              <p className="form-notice error" role="alert">
                {error}
              </p>
            )}
          </form>
          {local && (
            <details className="local-help">
              <summary>Autentificare locală</summary>
              <p>
                Folosește parola <code>ADMIN_PASSWORD</code> din <code>.env</code>. Repornește
                serverul dacă ai schimbat-o.
              </p>
            </details>
          )}
        </div>
      </section>
    </main>
  );
}

function Range({
  label,
  value,
  min,
  max,
  suffix,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  suffix: string;
  onChange: (value: number) => void;
}) {
  return (
    <label className="range-label">
      {label}
      <output>
        {value}
        {suffix}
      </output>
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
      />
    </label>
  );
}
function DesignControls({
  draft,
  options,
  onChange,
}: {
  draft: Draft;
  options: Dashboard['designOptions'];
  onChange: (draft: Draft) => void;
}) {
  const update = (values: Partial<Design>) =>
    onChange({ ...draft, design: { ...draft.design, ...values } });
  return (
    <div className="design-controls">
      <fieldset className="wide">
        <legend>Atmosferă vizuală</legend>
        <div className="template-grid">
          {options.templates.map((template) => (
            <button
              type="button"
              key={template}
              className={`template-chip theme-${template} ${draft.design.template === template ? 'selected' : ''}`}
              onClick={() => update({ template })}
            >
              <span />
              {template}
            </button>
          ))}
        </div>
      </fieldset>
      <label>
        Font
        <select value={draft.design.font} onChange={(e) => update({ font: e.target.value })}>
          {options.fonts.map((value) => (
            <option key={value}>{value}</option>
          ))}
        </select>
      </label>
      <label>
        Majuscule
        <select
          value={draft.design.textCase}
          onChange={(e) => update({ textCase: e.target.value })}
        >
          {options.textCases.map((value) => (
            <option key={value}>{value}</option>
          ))}
        </select>
      </label>
      <label>
        Poziție
        <select
          value={draft.design.textPosition}
          onChange={(e) => update({ textPosition: e.target.value })}
        >
          {options.textPositions.map((value) => (
            <option key={value}>{value}</option>
          ))}
        </select>
      </label>
      <label>
        Aliniere
        <select
          value={draft.design.textAlign}
          onChange={(e) => update({ textAlign: e.target.value })}
        >
          {options.textAlignments.map((value) => (
            <option key={value}>{value}</option>
          ))}
        </select>
      </label>
      <Range
        label="Dimensiune"
        value={draft.design.fontSize}
        min={48}
        max={112}
        suffix="px"
        onChange={(fontSize) => update({ fontSize })}
      />
      <Range
        label="Spațiere litere"
        value={draft.design.letterSpacing}
        min={-2}
        max={12}
        suffix="px"
        onChange={(letterSpacing) => update({ letterSpacing })}
      />
      <Range
        label="Înălțime rând"
        value={draft.design.lineHeight}
        min={90}
        max={160}
        suffix="%"
        onChange={(lineHeight) => update({ lineHeight })}
      />
      <Range
        label="Overlay"
        value={draft.design.overlayOpacity}
        min={0}
        max={65}
        suffix="%"
        onChange={(overlayOpacity) => update({ overlayOpacity })}
      />
      {draft.format === 'reel' && (
        <>
          <label>
            Animație
            <select
              value={draft.design.animation}
              onChange={(e) => update({ animation: e.target.value })}
            >
              {options.animations.map((value) => (
                <option key={value}>{value}</option>
              ))}
            </select>
          </label>
          <label>
            Soundscape
            <select value={draft.design.music} onChange={(e) => update({ music: e.target.value })}>
              {options.music.map((value) => (
                <option key={value}>{value}</option>
              ))}
            </select>
          </label>
          <SoundscapePreview music={draft.design.music} volume={draft.design.musicVolume} />
          <p className="settings-note">
            Durata este calculată automat pentru citirea fiecărei scene.
          </p>
          <Range
            label="Volum"
            value={draft.design.musicVolume}
            min={0}
            max={100}
            suffix="%"
            onChange={(musicVolume) => update({ musicVolume })}
          />
        </>
      )}
    </div>
  );
}
function VisualPreview({ draft, branding }: { draft: Draft; branding: Dashboard['branding'] }) {
  const [clock, setClock] = useState(0);
  let plan: ReturnType<typeof planReel> | null = null,
    error = '';
  try {
    if (draft.format === 'reel') plan = planReel(draft.quote, draft.design);
  } catch (reason) {
    error = reason instanceof Error ? reason.message : 'Simplifică textul.';
  }
  useEffect(() => {
    const start = performance.now();
    const timer = window.setInterval(() => setClock((performance.now() - start) / 1000), 33);
    return () => clearInterval(timer);
  }, [draft.quote, draft.format]);
  const t = plan ? clock % plan.duration : 0;
  const scene = plan?.scenes.find((s) => t >= s.start && t < s.end);
  const opacity = scene
    ? Math.max(0, Math.min(1, (t - scene.start) / 0.35, (scene.end - t) / 0.4))
    : 0;
  const fonts: Record<string, string> = {
    sans: 'Studio Sans',
    serif: 'Studio Serif',
    mono: 'Studio Mono',
  };
  const style = {
    textAlign: draft.design.textAlign as 'left' | 'center' | 'right',
    fontFamily: fonts[draft.design.font],
    fontSize: `${Math.max(17, draft.design.fontSize / 3)}px`,
    letterSpacing: `${draft.design.letterSpacing / 3}px`,
    lineHeight: draft.design.lineHeight / 100,
    textTransform:
      draft.design.textCase === 'uppercase' ? ('uppercase' as const) : ('none' as const),
    opacity: plan ? opacity : 1,
    transform: plan ? `translateY(${(1 - opacity) * 2.7}px)` : undefined,
  };
  return (
    <>
      <div
        className={`post-preview ${draft.format} theme-${draft.design.template} position-${draft.design.textPosition}`}
        style={{ '--overlay': draft.design.overlayOpacity / 100 } as React.CSSProperties}
      >
        <span className="preview-mark">{branding.name.toUpperCase()}</span>
        <div className="preview-message" style={style}>
          <p>{plan ? scene?.text || '' : draft.quote}</p>
          <span
            className={`accent-line align-${draft.design.textAlign}`}
            style={{ background: draft.accent }}
          />
        </div>
        <small>@{branding.username}</small>
      </div>
      {plan && (
        <p className="settings-note">
          {plan.mood} · {plan.scenes.length} scene · {plan.duration}s · Preview de timing. Randarea
          exactă și sunetul sunt disponibile din Content.
        </p>
      )}
      {error && <p role="alert">{error}</p>}
    </>
  );
}

function DashboardApp({ onLogout }: { onLogout: () => void }) {
  const [refreshingReels, setRefreshingReels] = useState(false);
  const [data, setData] = useState<Dashboard>(initialDashboard);
  const [page, setPage] = useState<Page>(currentPage);
  const [draft, setDraft] = useState<Draft>(initialDraft);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState('');
  const [previewPost, setPreviewPost] = useState<Post | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [editing, setEditing] = useState<Post | null>(null);
  const [editDraft, setEditDraft] = useState<Draft | null>(null);
  const [filter, setFilter] = useQueryPreference('status', 'all');
  const [search, setSearch] = useQueryPreference('q', '');
  const [contentFormat, setContentFormat] = useQueryPreference('format', 'all');
  const [collapsed, setCollapsed] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [dashboardLoading, setDashboardLoading] = useState(true);
  async function refresh() {
    try {
      const response = await fetch('/api/dashboard');
      if (response.status === 401) return onLogout();
      setData({ ...initialDashboard, ...(await responseJson(response)) });
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Serverul nu este disponibil.');
    } finally {
      setDashboardLoading(false);
    }
  }
  useEffect(() => {
    refresh();
    const interval = window.setInterval(refresh, 30_000);
    return () => window.clearInterval(interval);
  }, []);
  useEffect(() => {
    const handler = () => setPage(currentPage());
    addEventListener('hashchange', handler);
    return () => removeEventListener('hashchange', handler);
  }, []);
  const go = (next: Page) => {
    setMobileNav(false);
    location.hash = next;
    setPage(next);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
  const scheduled = data.posts.filter((post) => post.status === 'scheduled'),
    published = data.posts.filter((post) => post.status === 'published'),
    nextPost = scheduled[0];
  const filteredPosts = data.posts.filter(
    (post) =>
      (contentFormat === 'all' || post.format === contentFormat) &&
      (filter === 'all' || post.status === filter) &&
      `${post.quote} ${post.caption}`.toLowerCase().includes(search.toLowerCase()),
  );
  const automationHealthy = Boolean(
    data.automation.lastRun?.lastSuccessAt &&
    Date.now() - new Date(data.automation.lastRun.lastSuccessAt).getTime() < 5 * 60_000,
  );
  const recentDays = useMemo(
    () =>
      Array.from({ length: 7 }, (_, index) => {
        const date = new Date();
        date.setDate(date.getDate() - (6 - index));
        const key = dateKey(date.toISOString());
        return {
          key,
          label: new Intl.DateTimeFormat('ro-RO', { weekday: 'short' }).format(date),
          count: published.filter((post) => post.publishedAt && dateKey(post.publishedAt) === key)
            .length,
        };
      }),
    [data.posts],
  );
  const maxDaily = Math.max(1, ...recentDays.map((day) => day.count));
  async function createPost(event: FormEvent) {
    event.preventDefault();
    setSaving(true);
    setNotice('');
    try {
      await responseJson(
        await fetch('/api/posts', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            ...draft,
            scheduledFor: new Date(draft.scheduledFor).toISOString(),
          }),
        }),
      );
      setNotice(`${draft.format === 'reel' ? 'Reel-ul' : 'Postarea'} a fost adăugat în program.`);
      await refresh();
      go('planner');
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Conținutul nu a putut fi creat.');
    } finally {
      setSaving(false);
    }
  }
  async function randomize() {
    try {
      const idea = await responseJson(await fetch(`/api/ideas/random?format=${draft.format}`));
      setDraft((current) => ({
        ...current,
        ...idea,
        design: { ...current.design, ...idea.design },
      }));
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Ideea nu a putut fi generată.');
    }
  }
  async function updateSettings(values: Partial<Dashboard['settings']>) {
    setData((current) => ({ ...current, settings: { ...current.settings, ...values } }));
    try {
      await responseJson(
        await fetch('/api/settings', {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(values),
        }),
      );
      await refresh();
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Setările nu au putut fi salvate.');
    }
  }
  async function action(url: string, method = 'POST', success = 'Gata.') {
    setNotice('Se procesează…');
    try {
      await responseJson(await fetch(url, { method }));
      setNotice(success);
      await refresh();
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Acțiunea a eșuat.');
    }
  }
  async function removePost(post: Post) {
    if (!confirm(`Ștergi „${post.quote}”?`)) return;
    const response = await fetch(`/api/posts/${post.id}`, { method: 'DELETE' });
    if (!response.ok)
      return setNotice((await response.json().catch(() => ({}))).error || 'Nu a putut fi șters.');
    setNotice('Conținutul a fost șters.');
    await refresh();
  }
  async function openPreview(id: string) {
    setPreviewLoading(true);
    setPreviewPost(null);
    try {
      setPreviewPost(
        await responseJson(await fetch(`/api/posts/${id}/preview`, { method: 'POST' })),
      );
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Preview indisponibil.');
    } finally {
      setPreviewLoading(false);
    }
  }
  function openEditor(post: Post) {
    setEditing(post);
    setEditDraft({
      quote: post.quote,
      caption: post.caption,
      accent: post.accent,
      format: post.format,
      scheduledFor: isoToLocalInput(post.scheduledFor),
      design: { ...post.design },
    });
  }
  async function saveEdit(event: FormEvent) {
    event.preventDefault();
    if (!editing || !editDraft) return;
    setSaving(true);
    try {
      await responseJson(
        await fetch(`/api/posts/${editing.id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            ...editDraft,
            scheduledFor: new Date(editDraft.scheduledFor).toISOString(),
          }),
        }),
      );
      setEditing(null);
      setEditDraft(null);
      setNotice('Modificările au fost salvate.');
      await refresh();
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Modificările nu au putut fi salvate.');
    } finally {
      setSaving(false);
    }
  }
  async function refreshReels() {
    if (refreshingReels) return;
    setRefreshingReels(true);
    let refreshed = 0,
      failed = 0;
    try {
      const { ids } = await responseJson(
        await fetch('/api/queue/refresh-reels', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: '{}',
        }),
      );
      for (const id of ids) {
        setNotice(`Regenerare ${refreshed + failed + 1}/${ids.length}… Păstrează pagina deschisă.`);
        try {
          const result = await responseJson(
            await fetch('/api/queue/refresh-reels', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ id }),
            }),
          );
          if (result.status === 'refreshed') refreshed++;
          else failed++;
        } catch {
          failed++;
        }
      }
      setNotice(
        `${refreshed} Reel-uri regenerate. ${failed} neregenerate. Programarea a fost păstrată.`,
      );
      await refresh();
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Regenerarea a eșuat.');
    } finally {
      setRefreshingReels(false);
    }
  }
  async function rebuildQueue() {
    if (
      !confirm(
        'Reconstruiești toate postările generate automat din viitor după noul plan: 3 Reel-uri/zi și 2 postări/săptămână? Conținutul creat manual rămâne neatins.',
      )
    )
      return;
    await action('/api/queue/rebuild', 'POST', 'Calendarul automat a fost reconstruit.');
  }
  async function logout() {
    await fetch('/api/auth/logout', { method: 'POST' });
    onLogout();
  }
  const meta = pageMeta[page];
  const startCreate = (format: Format) => {
    setDraft((current) => ({ ...current, format }));
    go('studio');
  };
  const navItem = (item: Page, icon: string) => (
    <button
      key={item}
      title={pageMeta[item].label}
      aria-current={page === item ? 'page' : undefined}
      className={page === item ? 'active' : ''}
      onClick={() => go(item)}
    >
      <Icon name={icon} />
      <span className="nav-label">{pageMeta[item].label}</span>
      {item === 'planner' && <small className="nav-count">{data.posts.length}</small>}
    </button>
  );
  return (
    <div
      className={`app-shell ${collapsed ? 'nav-collapsed' : ''} ${mobileNav ? 'mobile-nav-open' : ''}`}
    >
      {mobileNav && (
        <button
          className="nav-scrim"
          aria-label="Închide meniul"
          onClick={() => setMobileNav(false)}
        />
      )}
      <aside className="sidebar">
        <div className="sidebar-brand">
          <div className="brand">
            <span>SF</span>
            <div className="nav-label">
              <strong>SilentForward</strong>
              <small>CONTENT STUDIO</small>
            </div>
          </div>
          <button
            className="icon-button collapse-nav"
            title={collapsed ? 'Extinde meniul' : 'Restrânge meniul'}
            aria-label={collapsed ? 'Extinde meniul' : 'Restrânge meniul'}
            onClick={() => setCollapsed(!collapsed)}
          >
            <Icon name="sidebar" />
          </button>
          <button
            className="icon-button mobile-only"
            aria-label="Închide meniul"
            onClick={() => setMobileNav(false)}
          >
            <Icon name="close" />
          </button>
        </div>
        <nav aria-label="Navigare principală">
          <div className="nav-group">
            <p className="nav-heading">WORKSPACE</p>
            {navItem('overview', 'dashboard')}
            {navItem('planner', 'folder')}
            {page === 'planner' && !collapsed && (
              <div className="nav-subitems">
                {[
                  ['all', 'Tot conținutul'],
                  ['reel', 'Reels'],
                  ['post', 'Posts'],
                ].map(([value, label]) => (
                  <button
                    key={value}
                    className={contentFormat === value ? 'selected' : ''}
                    onClick={() => {
                      setContentFormat(value);
                      setMobileNav(false);
                    }}
                  >
                    {label}
                  </button>
                ))}
              </div>
            )}
            {navItem('calendar', 'calendar')}
            {navItem('analytics', 'chart')}
          </div>
          <div className="nav-group">
            <p className="nav-heading">CREATIVE</p>
            {navItem('studio', 'plus')}
            <a href="/video-editor" title="Video Editor">
              <Icon name="video" />
              <span className="nav-label">Video Editor</span>
            </a>
            {navItem('library', 'templates')}
          </div>
          <div className="nav-group">
            <p className="nav-heading">MANAGE</p>
            {navItem('automation', 'bolt')}
            {navItem('settings', 'settings')}
          </div>
        </nav>
        <div className="sidebar-bottom">
          <div
            className="sidebar-status"
            title={automationHealthy ? 'Automatizarea este activă' : 'Verifică automatizarea'}
          >
            <i className={automationHealthy ? 'online' : ''} />
            <span className="nav-label">
              {automationHealthy ? 'Automatizare activă' : 'Necesită atenție'}
            </span>
          </div>
          <div className="account-card">
            <span className="avatar">SF</span>
            <div className="nav-label">
              <strong>@{data.account.username}</strong>
              <small>{data.account.accountType}</small>
            </div>
            <button
              className="icon-button"
              title="Deconectare"
              aria-label="Deconectare"
              onClick={logout}
            >
              <Icon name="logout" />
            </button>
          </div>
        </div>
      </aside>
      <div className="workspace">
        <div className="topbar">
          <div className="breadcrumb">
            <button
              className="icon-button mobile-only"
              aria-label="Deschide meniul"
              onClick={() => setMobileNav(true)}
            >
              <Icon name="menu" />
            </button>
            <span>Workspace</span>
            <Icon name="chevron" size={13} />
            <strong>{meta.label}</strong>
          </div>
          <div className="topbar-right">
            <span className="workspace-name">@{data.account.username}</span>
            <ThemeToggle />
            <FloatingMenu
              className="create-popover"
              label="Creează conținut"
              width={285}
              trigger={
                <>
                  <Icon name="plus" size={16} /> Create
                </>
              }
            >
              <button role="menuitem" onClick={() => startCreate('reel')}>
                <Icon name="video" />
                <span>
                  Generează Reel<small>Video vertical, pregătit pentru Instagram</small>
                </span>
              </button>
              <button role="menuitem" onClick={() => startCreate('post')}>
                <Icon name="image" />
                <span>
                  Creează postare<small>O idee, un vizual, un mesaj</small>
                </span>
              </button>
              <a role="menuitem" href="/video-editor">
                <Icon name="import" />
                <span>
                  Deschide Video Editor<small>Importă și montează propriul conținut</small>
                </span>
              </a>
            </FloatingMenu>
          </div>
        </div>
        <main className="dashboard-main">
          <header className="page-header">
            <div>
              <p className="eyebrow">{meta.eyebrow}</p>
              <h1>{meta.title}</h1>
              <p>{meta.description}</p>
            </div>
            <div className="header-actions">
              {page === 'overview' && (
                <button className="secondary" onClick={() => go('calendar')}>
                  <Icon name="calendar" /> Vezi calendarul
                </button>
              )}
              {page === 'analytics' && (
                <button
                  className="secondary"
                  onClick={() =>
                    action('/api/insights/refresh', 'POST', 'Datele au fost actualizate.')
                  }
                >
                  <Icon name="replay" /> Actualizează insights
                </button>
              )}
            </div>
          </header>
          {notice && (
            <section className="global-notice" role="status">
              <Icon name="info" />
              <span>{notice}</span>
              <button
                className="icon-button"
                aria-label="Închide notificarea"
                onClick={() => setNotice('')}
              >
                <Icon name="close" size={16} />
              </button>
            </section>
          )}
          {dashboardLoading ? (
            <DashboardSkeleton />
          ) : (
            <>
              {page === 'overview' && (
                <>
                  <section
                    className={`system-banner ${automationHealthy && data.publishingReady ? 'healthy' : 'warning'}`}
                  >
                    <div>
                      <span className="pulse-dot" />
                      <strong>
                        {automationHealthy && data.publishingReady
                          ? 'Feed + Stories publicate automat'
                          : 'Configurarea are nevoie de atenție'}
                      </strong>
                      <p>
                        {automationHealthy
                          ? `Ultima verificare: ${formatDate(data.automation.lastRun?.lastSuccessAt)}`
                          : data.automation.lastRun?.lastError || 'Workerul nu a răspuns recent.'}
                      </p>
                    </div>
                    <button className="text-link" onClick={() => go('automation')}>
                      Gestionează <Icon name="chevron" size={14} />
                    </button>
                  </section>
                  <section className="metrics">
                    <Metric
                      label="Programate"
                      value={data.stats.scheduled}
                      detail="în coada remote"
                      trend={`${scheduled.filter((post) => post.format === 'reel').length} Reel-uri`}
                    />
                    <Metric
                      label="Publicate"
                      value={data.stats.published}
                      detail={`${data.stats.storiesPublished} Stories promo`}
                      trend="Feed + Story"
                    />
                    <Metric
                      label="Erori"
                      value={data.stats.failed + data.stats.storiesFailed}
                      detail={
                        data.stats.storiesFailed
                          ? `${data.stats.storiesFailed} la Story`
                          : 'feed și stories curate'
                      }
                      trend={data.stats.failed + data.stats.storiesFailed ? 'Verifică' : 'Curat'}
                    />
                    <Metric
                      label="Următoarea"
                      value={
                        nextPost
                          ? formatDate(nextPost.scheduledFor, { day: '2-digit', month: 'short' })
                          : '—'
                      }
                      detail={
                        nextPost
                          ? `${nextPost.format === 'reel' ? 'Reel' : 'Postare'} · ${formatDate(nextPost.scheduledFor, { hour: '2-digit', minute: '2-digit' }).split(',').at(-1)}`
                          : 'coadă goală'
                      }
                      trend="Auto"
                    />
                  </section>
                  <section className="overview-grid">
                    <div className="panel">
                      <SectionHead
                        eyebrow="NEXT UP"
                        title="Urmează în calendar"
                        action={
                          <button className="text-link" onClick={() => go('planner')}>
                            Vezi tot →
                          </button>
                        }
                      />
                      <div className="pipeline">
                        {scheduled.slice(0, 6).map((post, index) => (
                          <button key={post.id} onClick={() => openEditor(post)}>
                            <span className="slot-index">{String(index + 1).padStart(2, '0')}</span>
                            <span className={`format-icon ${post.format}`}>
                              <Icon name={post.format === 'reel' ? 'video' : 'image'} />
                            </span>
                            <span>
                              <strong>{post.quote}</strong>
                              <small>
                                {formatDate(post.scheduledFor)} · {post.design.template} · + Story
                              </small>
                            </span>
                            <i className="mini-accent" style={{ background: post.accent }} />
                          </button>
                        ))}
                        {!scheduled.length && (
                          <EmptyState
                            title="Calendarul tău începe aici"
                            description="Creează primul conținut și alege când să apară."
                            action={
                              <button className="primary" onClick={() => startCreate('reel')}>
                                Creează un Reel
                              </button>
                            }
                          />
                        )}
                      </div>
                    </div>
                    <div className="panel">
                      <SectionHead eyebrow="7 DAYS" title="Ritmul publicărilor" />
                      <div className="bar-chart">
                        {recentDays.map((day) => (
                          <div key={day.key}>
                            <span className="bar-track">
                              <i
                                style={{ height: `${Math.max(8, (day.count / maxDaily) * 100)}%` }}
                              />
                            </span>
                            <strong>{day.count}</strong>
                            <small>{day.label}</small>
                          </div>
                        ))}
                      </div>
                      <div className="plan-summary">
                        <span>
                          <strong>{data.contentPlan.reelsPerDay}</strong>
                          <small>Reels / zi</small>
                        </span>
                        <span>
                          <strong>{data.contentPlan.postsPerWeek}</strong>
                          <small>Postări / săpt.</small>
                        </span>
                        <span>
                          <strong>1:1</strong>
                          <small>Story promo</small>
                        </span>
                      </div>
                    </div>
                  </section>
                </>
              )}
              {page === 'planner' && (
                <Planner
                  posts={filteredPosts}
                  format={contentFormat}
                  onFormat={setContentFormat}
                  onCreate={() => startCreate('reel')}
                  filter={filter}
                  search={search}
                  onFilter={setFilter}
                  onSearch={setSearch}
                  onPreview={openPreview}
                  onEdit={openEditor}
                  onPublish={(post) =>
                    action(`/api/posts/${post.id}/publish`, 'POST', 'Publicarea a pornit.')
                  }
                  onStory={(post) =>
                    action(
                      `/api/posts/${post.id}/story/publish`,
                      'POST',
                      'Story-ul promo a fost publicat.',
                    )
                  }
                  onRemove={removePost}
                  onDuplicate={(post) =>
                    action(`/api/posts/${post.id}/duplicate`, 'POST', 'Copia a fost creată.')
                  }
                />
              )}
              {page === 'calendar' && (
                <ContentCalendar
                  posts={data.posts}
                  onPreview={openPreview}
                  onCreate={() => startCreate('reel')}
                />
              )}
              {page === 'studio' && (
                <Studio
                  draft={draft}
                  setDraft={setDraft}
                  options={data.designOptions}
                  branding={data.branding}
                  saving={saving}
                  onSubmit={createPost}
                  onRandomize={randomize}
                />
              )}
              {page === 'library' && (
                <Library
                  options={data.designOptions}
                  onTemplate={(template) => {
                    setDraft((current) => ({
                      ...current,
                      design: { ...current.design, template },
                    }));
                    go('studio');
                  }}
                  posts={data.posts}
                  onPreview={openPreview}
                  onReuse={(post) => {
                    setDraft({
                      quote: post.quote,
                      caption: post.caption,
                      accent: post.accent,
                      format: post.format,
                      scheduledFor: localInput(),
                      design: { ...post.design },
                    });
                    go('studio');
                  }}
                  onIdea={async () => {
                    await randomize();
                    go('studio');
                  }}
                />
              )}
              {page === 'analytics' && <Analytics posts={data.posts} recentDays={recentDays} />}
              {(page === 'settings' || page === 'automation') && (
                <Settings
                  section={page}
                  data={data}
                  automationHealthy={automationHealthy}
                  onUpdate={updateSettings}
                  onRebuild={rebuildQueue}
                  onRefresh={refreshReels}
                  refreshing={refreshingReels}
                />
              )}
            </>
          )}
        </main>
      </div>
      {(previewLoading || previewPost) && (
        <PreviewModal
          loading={previewLoading}
          post={previewPost}
          onClose={() => !previewLoading && setPreviewPost(null)}
          onError={() => setNotice('Videoclipul nu a putut fi încărcat.')}
        />
      )}
      {editing && editDraft && (
        <EditModal
          draft={editDraft}
          setDraft={setEditDraft}
          options={data.designOptions}
          saving={saving}
          onSubmit={saveEdit}
          onClose={() => {
            setEditing(null);
            setEditDraft(null);
          }}
        />
      )}
    </div>
  );
}

function Metric({
  label,
  value,
  detail,
  trend,
}: {
  label: string;
  value: string | number;
  detail: string;
  trend: string;
}) {
  return (
    <article>
      <div>
        <span>{label}</span>
        <em>{trend}</em>
      </div>
      <strong>{value}</strong>
      <small>{detail}</small>
    </article>
  );
}
function SectionHead({
  eyebrow,
  title,
  action,
}: {
  eyebrow: string;
  title: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="section-heading">
      <div>
        <p className="eyebrow">{eyebrow}</p>
        <h2>{title}</h2>
      </div>
      {action}
    </div>
  );
}
function Studio({
  draft,
  setDraft,
  options,
  branding,
  saving,
  onSubmit,
  onRandomize,
}: {
  draft: Draft;
  setDraft: (draft: Draft) => void;
  options: Dashboard['designOptions'];
  branding: Dashboard['branding'];
  saving: boolean;
  onSubmit: (event: FormEvent) => void;
  onRandomize: () => void;
}) {
  return (
    <section className="studio-layout">
      <div className="panel composer">
        <SectionHead
          eyebrow="CREATIVE CONTROLS"
          title="Ideea ta, în prim-plan"
          action={
            <div className="heading-actions">
              <button className="secondary" type="button" onClick={onRandomize}>
                Generează idee
              </button>
              <span className="badge">Quiet ambition</span>
            </div>
          }
        />
        <form onSubmit={onSubmit}>
          <div className="format-tabs">
            {(['reel', 'post'] as Format[]).map((format) => (
              <button
                type="button"
                key={format}
                className={draft.format === format ? 'active' : ''}
                onClick={() => setDraft({ ...draft, format })}
              >
                {format === 'reel' ? 'Reel 9:16' : 'Postare 4:5'}
              </button>
            ))}
          </div>
          {draft.design.growth && (
            <div className="growth-brief">
              <span>
                <small>Hook</small>
                <strong>{draft.design.growth.hook}</strong>
              </span>
              <span>
                <small>Obiectiv</small>
                <strong>{draft.design.growth.objective}</strong>
              </span>
              <span>
                <small>Shareability</small>
                <strong>{draft.design.growth.shareabilityScore}/100</strong>
              </span>
            </div>
          )}
          <label>
            Mesaj
            <textarea
              className="quote-input"
              value={draft.quote}
              onChange={(e) => setDraft({ ...draft, quote: e.target.value })}
              maxLength={220}
              required
            />
            <small className="counter">{draft.quote.length}/220</small>
          </label>
          <label>
            Descriere Instagram
            <textarea
              className="caption"
              value={draft.caption}
              onChange={(e) => setDraft({ ...draft, caption: e.target.value })}
              maxLength={2200}
            />
          </label>
          <fieldset>
            <legend>Accent</legend>
            <div className="colors">
              {accents.map((color) => (
                <button
                  type="button"
                  key={color}
                  aria-label={`Accent ${color}`}
                  aria-pressed={draft.accent === color}
                  className={draft.accent === color ? 'selected' : ''}
                  style={{ background: color }}
                  onClick={() => setDraft({ ...draft, accent: color })}
                />
              ))}
            </div>
          </fieldset>
          <details className="design-disclosure" open>
            <summary>
              <Icon name="settings" /> Stil, imagine și sunet
              <Icon name="chevron" size={15} />
            </summary>
            <DesignControls draft={draft} options={options} onChange={setDraft} />
          </details>
          <div className="publish-row">
            <label>
              Data și ora
              <input
                type="datetime-local"
                value={draft.scheduledFor}
                min={localInput(new Date())}
                onChange={(e) => setDraft({ ...draft, scheduledFor: e.target.value })}
                required
              />
            </label>
            <button className="primary" disabled={saving}>
              {saving
                ? 'Se salvează…'
                : `Programează ${draft.format === 'reel' ? 'Reel-ul' : 'postarea'}`}
            </button>
          </div>
        </form>
      </div>
      <aside className="preview-column">
        <div className="preview-toolbar">
          <span>Live preview</span>
          <i>1080 × {draft.format === 'reel' ? '1920' : '1350'}</i>
        </div>
        <VisualPreview draft={draft} branding={branding} />
        <div className="preview-specs">
          <span>{draft.design.growth?.recipe || draft.design.template}</span>
          <span>{draft.design.animation}</span>
          <span>{draft.design.duration}s</span>
          <span>{draft.design.music}</span>
        </div>
      </aside>
    </section>
  );
}
function Planner({
  posts,
  filter,
  search,
  format,
  onFilter,
  onSearch,
  onFormat,
  onCreate,
  onPreview,
  onEdit,
  onPublish,
  onStory,
  onRemove,
  onDuplicate,
}: {
  posts: Post[];
  filter: string;
  search: string;
  format: string;
  onFilter: (value: string) => void;
  onSearch: (value: string) => void;
  onFormat: (value: string) => void;
  onCreate: () => void;
  onPreview: (id: string) => void;
  onEdit: (post: Post) => void;
  onPublish: (post: Post) => void;
  onStory: (post: Post) => void;
  onRemove: (post: Post) => void;
  onDuplicate: (post: Post) => void;
}) {
  const [view, setView] = useQueryPreference('view', 'table');
  const [source, setSource] = useQueryPreference('source', 'all');
  const [sort, setSort] = useQueryPreference('sort', 'schedule');
  const visible = posts
    .filter((p) => source === 'all' || (source === 'auto' ? p.autoGenerated : !p.autoGenerated))
    .slice()
    .sort(
      (a, b) =>
        (new Date(a.scheduledFor).getTime() - new Date(b.scheduledFor).getTime()) *
        (sort === 'latest' ? -1 : 1),
    );
  const active = filter !== 'all' || format !== 'all' || source !== 'all' || Boolean(search);
  const reset = () => {
    onFilter('all');
    onFormat('all');
    onSearch('');
    setSource('all');
  };
  const actions = (post: Post) => (
    <div className="row-actions">
      <button className="secondary" onClick={() => onPreview(post.id)}>
        <Icon name="play" size={14} /> Preview
      </button>
      <FloatingMenu
        className="row-popover"
        label={`Acțiuni pentru ${post.quote}`}
        width={190}
        trigger={<Icon name="more" />}
      >
        {['scheduled', 'failed'].includes(post.status) && (
          <>
            <button role="menuitem" onClick={() => onEdit(post)}>
              <Icon name="settings" /> Editează
            </button>
            <button role="menuitem" onClick={() => onPublish(post)}>
              <Icon name="export" /> Publică acum
            </button>
          </>
        )}
        {post.status === 'published' && post.design.story?.status !== 'published' && (
          <button role="menuitem" onClick={() => onStory(post)}>
            <Icon name="export" /> Publică Story
          </button>
        )}
        <button role="menuitem" onClick={() => onDuplicate(post)}>
          <Icon name="copy" /> Duplică
        </button>
        {['scheduled', 'failed'].includes(post.status) && (
          <button role="menuitem" className="destructive" onClick={() => onRemove(post)}>
            <Icon name="trash" /> Șterge
          </button>
        )}
      </FloatingMenu>
    </div>
  );
  return (
    <section className="content-manager">
      <div className="content-tabs" role="group" aria-label="Tip conținut">
        {[
          ['all', 'Tot conținutul'],
          ['reel', 'Reels'],
          ['post', 'Posts'],
        ].map(([value, label]) => (
          <button
            key={value}
            className={format === value ? 'active' : ''}
            aria-pressed={format === value}
            onClick={() => onFormat(value)}
          >
            {label}
          </button>
        ))}
      </div>
      <div className="content-toolbar">
        <label className="search-control">
          <Icon name="search" />
          <input
            type="search"
            aria-label="Caută în conținut"
            placeholder="Caută un mesaj…"
            value={search}
            onChange={(e) => onSearch(e.target.value)}
          />
        </label>
        <label className="filter-control">
          <span>Status</span>
          <select value={filter} onChange={(e) => onFilter(e.target.value)}>
            <option value="all">Toate</option>
            <option value="scheduled">Programat</option>
            <option value="publishing">Se publică</option>
            <option value="published">Publicat</option>
            <option value="failed">Eroare</option>
          </select>
        </label>
        <label className="filter-control">
          <span>Sursă</span>
          <select value={source} onChange={(e) => setSource(e.target.value)}>
            <option value="all">Toate</option>
            <option value="auto">Autopilot</option>
            <option value="manual">Manual</option>
          </select>
        </label>
        <label className="filter-control sort-control">
          <span>Ordine</span>
          <select value={sort} onChange={(e) => setSort(e.target.value)}>
            <option value="schedule">Programare ↑</option>
            <option value="latest">Programare ↓</option>
          </select>
        </label>
        <div className="view-toggle" aria-label="Mod afișare">
          <button
            aria-label="Tabel"
            aria-pressed={view !== 'grid'}
            className={view !== 'grid' ? 'active' : ''}
            onClick={() => setView('table')}
          >
            <Icon name="list" />
          </button>
          <button
            aria-label="Grilă"
            aria-pressed={view === 'grid'}
            className={view === 'grid' ? 'active' : ''}
            onClick={() => setView('grid')}
          >
            <Icon name="templates" />
          </button>
        </div>
      </div>
      <div className="results-summary">
        <span>
          {visible.length} {visible.length === 1 ? 'element' : 'elemente'}
          {active ? ' · filtre active' : ''}
        </span>
        {active && (
          <button className="text-link" onClick={reset}>
            Resetează filtrele <Icon name="close" size={13} />
          </button>
        )}
      </div>
      {!visible.length ? (
        <EmptyState
          title={active ? 'Niciun rezultat' : 'Primul tău conținut începe cu o idee'}
          description={
            active
              ? 'Încearcă alte filtre sau un alt cuvânt.'
              : 'Generează un Reel și adaugă-l în calendar.'
          }
          action={
            <button className="primary" onClick={active ? reset : onCreate}>
              {active ? 'Resetează filtrele' : 'Creează un Reel'}
            </button>
          }
        />
      ) : view === 'grid' ? (
        <div className="content-grid">
          {visible.map((post) => (
            <article className="content-card" key={post.id}>
              <button
                className={`card-visual theme-${post.design.template}`}
                onClick={() => onPreview(post.id)}
                aria-label={`Preview: ${post.quote}`}
              >
                <span>SILENTFORWARD</span>
                {post.format === 'post' && post.mediaUrl ? (
                  <img src={post.mediaUrl} alt={post.quote} loading="lazy" />
                ) : (
                  <strong>{post.quote}</strong>
                )}
                <span className="card-play">
                  <Icon name={post.format === 'reel' ? 'play' : 'image'} />
                </span>
              </button>
              <div className="content-card-body">
                <StatusBadge status={post.status} />
                <p>{post.quote}</p>
                <small>
                  {formatDate(post.scheduledFor)} · {post.autoGenerated ? 'Autopilot' : 'Manual'}
                </small>
                {post.error && <p className="form-notice error">{post.error}</p>}
                {post.design.story?.error && (
                  <p className="form-notice error">Story: {post.design.story.error}</p>
                )}
                {actions(post)}
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Conținut</th>
                <th>Format</th>
                <th>Programare</th>
                <th>Status</th>
                <th>
                  <span className="sr-only">Acțiuni</span>
                </th>
              </tr>
            </thead>
            <tbody>
              {visible.map((post) => (
                <tr key={post.id}>
                  <td>
                    <div className="table-content">
                      <span className={`table-thumb theme-${post.design.template}`}>
                        <Icon name={post.format === 'reel' ? 'video' : 'image'} />
                      </span>
                      <span className="content-cell">
                        <strong>{post.quote}</strong>
                        <small>
                          {post.autoGenerated ? 'Autopilot' : 'Manual'} · {post.design.template} ·
                          Story {post.design.story?.status || 'după publicare'}
                          {post.design.performance
                            ? ` · Scor ${post.design.performance.score}`
                            : ''}
                        </small>
                        {post.error && <em>{post.error}</em>}
                        {post.design.story?.error && <em>Story: {post.design.story.error}</em>}
                      </span>
                    </div>
                  </td>
                  <td>
                    <span className="format-badge">{post.format === 'reel' ? 'Reel' : 'Post'}</span>
                  </td>
                  <td className="date-cell">{formatDate(post.scheduledFor)}</td>
                  <td>
                    <StatusBadge status={post.status} />
                  </td>
                  <td>{actions(post)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

function ContentCalendar({
  posts,
  onPreview,
  onCreate,
}: {
  posts: Post[];
  onPreview: (id: string) => void;
  onCreate: () => void;
}) {
  const [month, setMonth] = useState(() => dateKey(new Date().toISOString()).slice(0, 7));
  const [view, setView] = useState('month');
  const [selectedDay, setSelectedDay] = useState('');
  const [year, number] = month.split('-').map(Number);
  const start = new Date(year, number - 1, 1),
    count = new Date(year, number, 0).getDate(),
    offset = (start.getDay() + 6) % 7;
  const monthly = posts
    .filter((p) => dateKey(p.scheduledFor).startsWith(month))
    .sort((a, b) => Date.parse(a.scheduledFor) - Date.parse(b.scheduledFor));
  const grouped = Object.entries(
    monthly.reduce<Record<string, Post[]>>((all, p) => {
      (all[dateKey(p.scheduledFor)] ||= []).push(p);
      return all;
    }, {}),
  );
  const changeMonth = (delta: number) => {
    const next = new Date(year, number - 1 + delta, 1);
    setMonth(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`);
    setSelectedDay('');
  };
  return (
    <section className="calendar-section">
      <div className="calendar-toolbar">
        <div className="calendar-navigation">
          <button
            className="icon-button"
            aria-label="Luna precedentă"
            onClick={() => changeMonth(-1)}
          >
            <Icon name="back" />
          </button>
          <h2>{start.toLocaleDateString('ro-RO', { month: 'long', year: 'numeric' })}</h2>
          <button
            className="icon-button"
            aria-label="Luna următoare"
            onClick={() => changeMonth(1)}
          >
            <Icon name="chevron" />
          </button>
          <button
            className="secondary"
            onClick={() => {
              setMonth(dateKey(new Date().toISOString()).slice(0, 7));
              setSelectedDay('');
            }}
          >
            Astăzi
          </button>
        </div>
        <div className="view-toggle">
          <button
            className={view === 'month' ? 'active' : ''}
            aria-pressed={view === 'month'}
            onClick={() => setView('month')}
          >
            Lună
          </button>
          <button
            className={view === 'list' ? 'active' : ''}
            aria-pressed={view === 'list'}
            onClick={() => setView('list')}
          >
            Listă
          </button>
        </div>
      </div>
      {view === 'month' && (
        <div className="calendar-scroll">
          <div className="calendar-grid">
            {['Lun', 'Mar', 'Mie', 'Joi', 'Vin', 'Sâm', 'Dum'].map((d) => (
              <div className="calendar-weekday" key={d}>
                {d}
              </div>
            ))}
            {Array.from({ length: offset }, (_, i) => (
              <div key={`blank-${i}`} className="calendar-day outside" />
            ))}
            {Array.from({ length: count }, (_, i) => {
              const key = `${month}-${String(i + 1).padStart(2, '0')}`,
                dayPosts = monthly.filter((p) => dateKey(p.scheduledFor) === key);
              return (
                <div
                  key={key}
                  className={`calendar-day ${selectedDay === key ? 'selected' : ''} ${dateKey(new Date().toISOString()) === key ? 'today' : ''}`}
                >
                  <button
                    className="day-number"
                    onClick={() => setSelectedDay(selectedDay === key ? '' : key)}
                    aria-label={`Vezi ${key}`}
                  >
                    {i + 1}
                  </button>
                  {dayPosts.slice(0, 3).map((post) => (
                    <button
                      key={post.id}
                      className={`calendar-event ${post.status}`}
                      onClick={() => onPreview(post.id)}
                      title={post.quote}
                    >
                      <i />
                      <time>
                        {new Date(post.scheduledFor).toLocaleTimeString('ro-RO', {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </time>
                      <span>{post.quote}</span>
                    </button>
                  ))}
                  {dayPosts.length > 3 && (
                    <button className="text-link more-events" onClick={() => setSelectedDay(key)}>
                      +{dayPosts.length - 3} elemente
                    </button>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
      <div className="calendar-list">
        {selectedDay && (
          <div className="results-summary">
            <strong>{selectedDay}</strong>
            <button className="text-link" onClick={() => setSelectedDay('')}>
              Toată luna
            </button>
          </div>
        )}
        {(view === 'list' || selectedDay) &&
          grouped
            .filter(([key]) => !selectedDay || key === selectedDay)
            .map(([key, dayPosts]) => (
              <section key={key} className="calendar-agenda">
                <h3>{shortDay(dayPosts[0].scheduledFor)}</h3>
                {dayPosts.map((post) => (
                  <button className="agenda-item" key={post.id} onClick={() => onPreview(post.id)}>
                    <time>
                      {new Date(post.scheduledFor).toLocaleTimeString('ro-RO', {
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </time>
                    <Icon name={post.format === 'reel' ? 'video' : 'image'} />
                    <strong>{post.quote}</strong>
                    <StatusBadge status={post.status} />
                  </button>
                ))}
              </section>
            ))}
      </div>
      {!monthly.length && (
        <EmptyState
          title="O lună plină de posibilități"
          description="Nu există conținut în această lună."
          action={
            <button className="primary" onClick={onCreate}>
              Creează conținut
            </button>
          }
        />
      )}
      {selectedDay && !grouped.some(([key]) => key === selectedDay) && (
        <p className="empty">Nu există conținut pentru această zi.</p>
      )}
    </section>
  );
}

function Library({
  posts,
  options,
  onPreview,
  onReuse,
  onIdea,
  onTemplate,
}: {
  posts: Post[];
  options: Dashboard['designOptions'];
  onPreview: (id: string) => void;
  onReuse: (post: Post) => void;
  onIdea: () => void;
  onTemplate: (template: string) => void;
}) {
  const [tab, setTab] = useState('content'),
    [music, setMusic] = useState(options.music.find((m) => m !== 'silent') || 'ambient');
  const published = posts
    .filter((p) => p.status === 'published')
    .slice()
    .reverse()
    .slice(0, 18);
  return (
    <>
      <div className="content-tabs">
        {[
          ['content', 'Conținut publicat'],
          ['templates', 'Templates'],
          ['music', 'Music'],
        ].map(([value, label]) => (
          <button
            key={value}
            className={tab === value ? 'active' : ''}
            aria-pressed={tab === value}
            onClick={() => setTab(value)}
          >
            {label}
          </button>
        ))}
      </div>
      {tab === 'content' && (
        <>
          <section className="library-hero">
            <div>
              <h2>Ideile bune merită să continue.</h2>
              <p>Reutilizează conținutul publicat sau începe cu un concept nou.</p>
            </div>
            <button className="secondary" onClick={onIdea}>
              <Icon name="effects" /> Generează o idee
            </button>
          </section>
          <section className="content-grid">
            {published.map((post) => (
              <article className="content-card" key={post.id}>
                <button
                  className={`card-visual theme-${post.design.template}`}
                  onClick={() => onPreview(post.id)}
                >
                  <span>{post.format === 'reel' ? 'REEL' : 'POST'}</span>
                  {post.format === 'post' && post.mediaUrl ? (
                    <img src={post.mediaUrl} alt={post.quote} loading="lazy" />
                  ) : (
                    <strong>{post.quote}</strong>
                  )}
                  <Icon name={post.format === 'reel' ? 'play' : 'image'} />
                </button>
                <div className="card-meta">
                  <span>{post.design.template}</span>
                  <button className="text-link" onClick={() => onReuse(post)}>
                    Reutilizează <Icon name="chevron" size={13} />
                  </button>
                </div>
              </article>
            ))}
          </section>
          {!published.length && (
            <EmptyState
              title="Biblioteca se construiește cu tine"
              description="Conținutul publicat va apărea aici, gata de reutilizare."
              action={
                <button className="primary" onClick={onIdea}>
                  Generează o idee
                </button>
              }
            />
          )}
        </>
      )}
      {tab === 'templates' && (
        <>
          <p className="section-description">
            Alege o atmosferă. Continuă personalizarea în studio.
          </p>
          <div className="template-library">
            {options.templates.map((template) => (
              <button
                className="template-library-card"
                key={template}
                onClick={() => onTemplate(template)}
              >
                <div className={`template-sample theme-${template}`}>
                  <small>SILENTFORWARD</small>
                  <strong>
                    Quiet work.
                    <br />
                    Visible results.
                  </strong>
                  <span />
                </div>
                <div>
                  <strong>{template}</strong>
                  <span>
                    Folosește <Icon name="chevron" size={14} />
                  </span>
                </div>
              </button>
            ))}
          </div>
        </>
      )}
      {tab === 'music' && (
        <section className="music-library">
          <div>
            <span className="music-library-icon">
              <Icon name="audio" size={32} />
            </span>
            <h2>Găsește tonul potrivit.</h2>
            <p>Ascultă soundscape-urile originale disponibile în generator.</p>
          </div>
          <div className="panel">
            <label>
              Soundscape
              <select value={music} onChange={(e) => setMusic(e.target.value)}>
                {options.music.map((value) => (
                  <option key={value} value={value}>
                    {value}
                  </option>
                ))}
              </select>
            </label>
            <SoundscapePreview music={music} volume={60} />
            <p className="settings-note">
              Mostră audio de 8 secunde. Alege muzica pentru fiecare Reel din Create.
            </p>
          </div>
        </section>
      )}
    </>
  );
}

function Analytics({
  posts,
  recentDays,
}: {
  posts: Post[];
  recentDays: { key: string; label: string; count: number }[];
}) {
  const published = posts.filter((post) => post.status === 'published'),
    measured = published.filter((post) => post.design.performance),
    totalViews = measured.reduce((sum, post) => sum + (post.design.performance?.views || 0), 0),
    totalShares = measured.reduce((sum, post) => sum + (post.design.performance?.shares || 0), 0),
    totalSaves = measured.reduce((sum, post) => sum + (post.design.performance?.saved || 0), 0),
    measuredReels = measured.filter((post) => post.format === 'reel'),
    averageWatch =
      measuredReels.reduce(
        (sum, post) => sum + (post.design.performance?.averageWatchTimeMs || 0),
        0,
      ) /
      Math.max(1, measuredReels.length) /
      1000;
  const recipeGroups = measured.reduce<Record<string, { total: number; count: number }>>(
    (result, post) => {
      const recipe = post.design.growth?.recipe || post.design.template;
      const group = (result[recipe] ||= { total: 0, count: 0 });
      group.total += post.design.performance?.score || 0;
      group.count += 1;
      return result;
    },
    {},
  );
  const recipes = Object.entries(recipeGroups)
    .map(([recipe, value]) => [recipe, Math.round(value.total / value.count)] as const)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6);
  return (
    <>
      <section className="analytics-cards">
        <Metric
          label="Views măsurate"
          value={totalViews}
          detail={`${measured.length} materiale analizate`}
          trend="Insights"
        />
        <Metric label="Distribuiri" value={totalShares} detail="semnal de reach" trend="Priority" />
        <Metric
          label="Salvări"
          value={totalSaves}
          detail="valoare pe termen lung"
          trend="Quality"
        />
        <Metric
          label="Watch mediu"
          value={`${averageWatch.toFixed(1)}s`}
          detail="Reel-uri analizate"
          trend="Retention"
        />
      </section>
      <section className="analytics-grid">
        <div className="panel">
          <SectionHead eyebrow="OUTPUT" title="Ultimele 7 zile" />
          <div className="large-chart">
            {recentDays.map((day) => (
              <div key={day.key}>
                <span>
                  <i style={{ height: `${Math.max(4, day.count * 28)}px` }} />
                </span>
                <strong>{day.count}</strong>
                <small>{day.label}</small>
              </div>
            ))}
          </div>
          <div className="growth-signals">
            <span>
              <strong>Watch time</strong>
              <small>Hook în prima secundă</small>
            </span>
            <span>
              <strong>Shares</strong>
              <small>Mesaje trimise în DM</small>
            </span>
            <span>
              <strong>Saves</strong>
              <small>Idei de revăzut</small>
            </span>
          </div>
        </div>
        <div className="panel">
          <SectionHead eyebrow="GROWTH LAB" title="Rețete după performanță" />
          <div className="ranking">
            {recipes.map(([recipe, score], index) => (
              <div key={recipe}>
                <span>{index + 1}</span>
                <strong>{recipe}</strong>
                <i>
                  <b style={{ width: `${score}%` }} />
                </i>
                <em>{score}</em>
              </div>
            ))}
            {!recipes.length && (
              <p className="empty">Insights se colectează automat după publicare.</p>
            )}
          </div>
          <p className="settings-note">
            Motorul folosește 75% rețete validate și 25% experimente noi. Scorul combină retenția,
            distribuirile, salvările, aprecierile și comentariile.
          </p>
        </div>
      </section>
    </>
  );
}
function Settings({
  section,
  data,
  automationHealthy,
  onUpdate,
  onRebuild,
  onRefresh,
  refreshing,
}: {
  data: Dashboard;
  automationHealthy: boolean;
  onUpdate: (values: Partial<Dashboard['settings']>) => void;
  onRebuild: () => void;
  onRefresh: () => void;
  refreshing: boolean;
  section: 'settings' | 'automation';
}) {
  return (
    <section className="settings-layout">
      <aside className="settings-intro">
        <h2>{section === 'automation' ? 'Publică în ritmul tău' : 'Totul conectat'}</h2>
        <p>
          {section === 'automation'
            ? 'Controlează planul editorial și coada de conținut.'
            : 'Verifică starea contului și a conexiunilor existente.'}
        </p>
      </aside>
      <div className="settings-grid">
        {section === 'automation' && (
          <div className="panel">
            <SectionHead eyebrow="EDITORIAL CADENCE" title="Planul automat" />
            <div className="cadence-card">
              <div>
                <span>Reels</span>
                <strong>{data.contentPlan.reelsPerDay} / zi</strong>
                <small>Focus principal</small>
              </div>
              <div className="time-pills">
                {data.contentPlan.reelTimes.map((time) => (
                  <span key={time}>{time}</span>
                ))}
              </div>
            </div>
            <div className="cadence-card">
              <div>
                <span>Postări</span>
                <strong>{data.contentPlan.postsPerWeek} / săptămână</strong>
                <small>Conținut suport</small>
              </div>
              <div className="time-pills">
                {data.contentPlan.postWeekdays.map((day) => (
                  <span key={day}>{weekdays[day]}</span>
                ))}
              </div>
            </div>
            <div className="cadence-card story-cadence">
              <div>
                <span>Stories promo</span>
                <strong>După fiecare publicare</strong>
                <small>Format vertical 9:16 · retry separat</small>
              </div>
              <div className="time-pills">
                <span>100% AUTO</span>
              </div>
            </div>
            <div className="cadence-card growth-cadence">
              <div>
                <span>Growth Engine</span>
                <strong>Explore 25% · Exploit 75%</strong>
                <small>Învață din watch time, shares și saves</small>
              </div>
              <div className="time-pills">
                <span>v{data.contentPlan.growthStrategy}</span>
              </div>
            </div>
            <label className="setting-row">
              <span>
                <strong>Autopilot</strong>
                <small>Supabase verifică programul în fiecare minut.</small>
              </span>
              <input
                type="checkbox"
                checked={data.settings.autopilot}
                onChange={(e) => onUpdate({ autopilot: e.target.checked })}
              />
            </label>
            <label className="setting-row">
              <span>
                <strong>Orizontul cozii</strong>
                <small>Câte zile sunt pregătite în avans.</small>
              </span>
              <input
                type="number"
                min="3"
                max="30"
                value={data.settings.queueDays}
                onChange={(e) => onUpdate({ queueDays: Number(e.target.value) })}
              />
            </label>
            <label className="setting-row">
              <span>
                <strong>Ora postărilor statice</strong>
                <small>Marți și sâmbătă.</small>
              </span>
              <input
                type="time"
                value={data.settings.postTime}
                onChange={(e) => onUpdate({ postTime: e.target.value })}
              />
            </label>
            <details className="advanced-settings">
              <summary>Administrarea cozii</summary>
              <button className="secondary" disabled={refreshing} onClick={onRefresh}>
                {refreshing ? 'Se regenerează…' : 'Regenerează Reel-urile programate'}
              </button>
              <p className="settings-note">
                Păstrează data și ora. Înlocuiește doar Reel-uri viitoare generate, după validare.
              </p>
              <button className="secondary danger-button" onClick={onRebuild}>
                Reconstruiește coada automată
              </button>
              <p className="settings-note">
                Șterge numai elementele viitoare create de autopilot. Postările manuale și istoricul
                publicat rămân intacte.
              </p>
            </details>
          </div>
        )}
        {section === 'settings' && (
          <div className="panel">
            <SectionHead eyebrow="SYSTEM" title="Conexiuni și siguranță" />
            <div className="connection-list">
              <Connection
                name="Instagram Business"
                ok={data.account.connected}
                detail={`@${data.account.username}`}
              />
              <Connection
                name="Growth Insights"
                ok={data.publishingReady}
                detail={`${data.stats.insightsCollected} materiale măsurate · scor ${data.stats.averageGrowthScore}`}
              />
              <Connection
                name="Story autopilot"
                ok={data.contentPlan.storyAfterEveryPublication}
                detail="Promo după fiecare Reel și postare"
              />
              <Connection
                name="Vercel publisher"
                ok={data.publishingReady}
                detail="Randare serverless"
              />
              <Connection
                name="Supabase scheduler"
                ok={automationHealthy}
                detail="Verificare la fiecare minut"
              />
              <Connection
                name="Cloudinary CDN"
                ok={data.publishingReady}
                detail="Video și imagini publice"
              />
            </div>
            <div className="license-card">
              <strong>Soundscape-uri originale</strong>
              <p>
                Piesele incluse sunt generate de aplicație și evită problemele de copyright. Muzica
                comercială nu este copiată fără licență.
              </p>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
function Connection({ name, ok, detail }: { name: string; ok: boolean; detail: string }) {
  return (
    <div>
      <i className={ok ? 'ok' : ''} />
      <span>
        <strong>{name}</strong>
        <small>{detail}</small>
      </span>
      <em>{ok ? 'Connected' : 'Check'}</em>
    </div>
  );
}
function useModalDialog(onClose: () => void) {
  const dialog = useRef<HTMLElement>(null);
  const close = useRef(onClose);
  close.current = onClose;
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const overflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const focusable = () =>
      Array.from(
        dialog.current?.querySelectorAll<HTMLElement>(
          'button:not(:disabled), a[href], input:not(:disabled), select:not(:disabled), textarea:not(:disabled), summary, video[controls], [tabindex="0"]',
        ) || [],
      ).filter((element) => element.getClientRects().length);
    focusable()[0]?.focus();
    const handleKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.preventDefault();
        close.current();
      }
      if (event.key !== 'Tab') return;
      const items = focusable(),
        first = items[0],
        last = items[items.length - 1];
      if (!first) {
        event.preventDefault();
        return;
      }
      if (
        event.shiftKey &&
        (document.activeElement === first || !dialog.current?.contains(document.activeElement))
      ) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };
    document.addEventListener('keydown', handleKey);
    return () => {
      document.body.style.overflow = overflow;
      document.removeEventListener('keydown', handleKey);
      previous?.focus();
    };
  }, []);
  return dialog;
}
function PreviewModal({
  loading,
  post,
  onClose,
  onError,
}: {
  loading: boolean;
  post: Post | null;
  onClose: () => void;
  onError: () => void;
}) {
  const dialog = useModalDialog(onClose);
  return (
    <div className="modal-backdrop" onMouseDown={onClose}>
      <section
        ref={dialog}
        className="preview-modal"
        role="dialog"
        aria-modal="true"
        aria-label="Detalii conținut"
        onMouseDown={(e) => e.stopPropagation()}
      >
        <button
          className="modal-close icon-button"
          aria-label="Închide fereastra"
          onClick={onClose}
        >
          <Icon name="close" />
        </button>
        {loading ? (
          <div className="preview-loading">
            <div className="media-skeleton" />
            <strong>Se generează randarea exactă</strong>
            <small>Primul preview poate dura aproximativ 30 de secunde.</small>
          </div>
        ) : (
          post && (
            <>
              <div className="media-frame">
                {post.format === 'reel' ? (
                  <video
                    src={post.mediaUrl}
                    controls
                    autoPlay
                    muted
                    loop
                    playsInline
                    preload="auto"
                    onError={onError}
                  />
                ) : (
                  <img src={post.mediaUrl} alt={post.quote} />
                )}
              </div>
              <div className="preview-copy">
                <p className="eyebrow">DETALII CONȚINUT</p>
                <StatusBadge status={post.status} />
                <dl className="properties-list">
                  <div>
                    <dt>Programare</dt>
                    <dd>{formatDate(post.scheduledFor)}</dd>
                  </div>
                  <div>
                    <dt>Template</dt>
                    <dd>{post.design.template}</dd>
                  </div>
                  <div>
                    <dt>Muzică</dt>
                    <dd>{post.design.music}</dd>
                  </div>
                </dl>
                <span className="badge">
                  {post.format === 'reel'
                    ? `${post.design.animation} · ${post.design.duration}s · ${post.design.music}`
                    : `Post · ${post.design.template}`}
                </span>
                <h2>{post.quote}</h2>
                <p>{post.caption}</p>
              </div>
            </>
          )
        )}
      </section>
    </div>
  );
}
function EditModal({
  draft,
  setDraft,
  options,
  saving,
  onSubmit,
  onClose,
}: {
  draft: Draft;
  setDraft: (draft: Draft) => void;
  options: Dashboard['designOptions'];
  saving: boolean;
  onSubmit: (event: FormEvent) => void;
  onClose: () => void;
}) {
  const dialog = useModalDialog(onClose);
  return (
    <div className="modal-backdrop" onMouseDown={onClose}>
      <section
        ref={dialog}
        className="edit-modal"
        role="dialog"
        aria-modal="true"
        aria-label="Detalii conținut"
        onMouseDown={(e) => e.stopPropagation()}
      >
        <button
          className="modal-close icon-button"
          aria-label="Închide fereastra"
          onClick={onClose}
        >
          <Icon name="close" />
        </button>
        <SectionHead eyebrow="ADVANCED EDIT" title="Editează conținutul" />
        <form onSubmit={onSubmit}>
          <div className="form-row">
            <label>
              Format
              <select
                disabled={Boolean(draft.design.editorMedia)}
                value={draft.format}
                onChange={(e) => setDraft({ ...draft, format: e.target.value as Format })}
              >
                <option value="reel">Reel</option>
                <option value="post">Postare</option>
              </select>
            </label>
            <label>
              Data și ora
              <input
                type="datetime-local"
                value={draft.scheduledFor}
                onChange={(e) => setDraft({ ...draft, scheduledFor: e.target.value })}
              />
            </label>
          </div>
          <label>
            Mesaj
            <textarea
              value={draft.quote}
              onChange={(e) => setDraft({ ...draft, quote: e.target.value })}
              required
            />
          </label>
          <label>
            Descriere
            <textarea
              className="caption"
              value={draft.caption}
              onChange={(e) => setDraft({ ...draft, caption: e.target.value })}
            />
          </label>
          <fieldset>
            <legend>Accent</legend>
            <div className="colors">
              {accents.map((color) => (
                <button
                  type="button"
                  key={color}
                  style={{ background: color }}
                  aria-label={`Accent ${color}`}
                  aria-pressed={draft.accent === color}
                  className={draft.accent === color ? 'selected' : ''}
                  onClick={() => setDraft({ ...draft, accent: color })}
                />
              ))}
            </div>
          </fieldset>
          <>
            {draft.design.editorMedia ? (
              <p className="settings-note">
                Videoclip montat în Video Editor. Poți modifica titlul, descrierea și programarea;
                montajul video exportat este păstrat.
              </p>
            ) : (
              <DesignControls draft={draft} options={options} onChange={setDraft} />
            )}
          </>
          <button className="primary" disabled={saving}>
            {saving ? 'Se salvează…' : 'Salvează toate modificările'}
          </button>
        </form>
      </section>
    </div>
  );
}

function App() {
  const [session, setSession] = useState<'loading' | 'authenticated' | 'anonymous'>('loading');
  useEffect(() => {
    fetch('/api/auth/session')
      .then((response) => response.json())
      .then((result) => setSession(result.authenticated ? 'authenticated' : 'anonymous'))
      .catch(() => setSession('anonymous'));
  }, []);
  if (session === 'loading')
    return (
      <main className="splash">
        <div className="brand">
          <span>SF</span>
          <strong>Silent Forward</strong>
        </div>
      </main>
    );
  if (session === 'anonymous') return <Login onAuthenticated={() => setSession('authenticated')} />;
  if (window.location.pathname.replace(/\/$/, '') === '/video-editor')
    return (
      <Suspense fallback={<main className="splash">Opening Video Editor…</main>}>
        <VideoEditor />
      </Suspense>
    );
  return <DashboardApp onLogout={() => setSession('anonymous')} />;
}

export default App;
