import { FormEvent, useEffect, useMemo, useState } from 'react'

type Format = 'post' | 'reel'
type Design = {
  template: string
  font: string
  textPosition: string
  textAlign: string
  fontSize: number
  animation: string
  duration: number
  music: string
  musicVolume: number
}
type Post = {
  id: string
  quote: string
  caption: string
  accent: string
  format: Format
  status: 'scheduled' | 'publishing' | 'published' | 'failed'
  scheduledFor: string
  design: Design
  mediaUrl?: string
  instagramMediaId?: string
  error?: string
  autoGenerated?: boolean
}
type Dashboard = {
  account: { connected: boolean; username: string; accountType: string }
  publishingReady: boolean
  automation: {
    configured: boolean
    lastRun: null | {
      status: 'idle' | 'running' | 'succeeded' | 'failed'
      startedAt?: string
      finishedAt?: string
      lastSuccessAt?: string
      lastError?: string
    }
  }
  posts: Post[]
  settings: { autopilot: boolean; postTime: string; reelTime: string; timezone: string; queueDays: number }
  stats: { scheduled: number; published: number; failed: number }
  designOptions: {
    templates: string[]
    fonts: string[]
    textPositions: string[]
    textAlignments: string[]
    animations: string[]
    music: string[]
  }
}
type Draft = {
  quote: string
  caption: string
  accent: string
  format: Format
  scheduledFor: string
  design: Design
}

const accents = ['#d9ff3f', '#ff5c35', '#62e6ff', '#d8a7ff', '#ffcf5c', '#71f6a5', '#ff7eb6', '#ffffff']
const fallbackOptions = {
  templates: ['midnight', 'aurora', 'ember', 'ocean', 'monochrome', 'paper'],
  fonts: ['sans', 'serif', 'mono'],
  textPositions: ['top', 'center', 'bottom'],
  textAlignments: ['left', 'center', 'right'],
  animations: ['drift', 'zoom', 'slide', 'pulse', 'static'],
  music: ['ambient', 'deep', 'focus', 'pulse', 'silent'],
}
const defaultDesign: Design = {
  template: 'midnight', font: 'sans', textPosition: 'center', textAlign: 'left',
  fontSize: 76, animation: 'drift', duration: 8, music: 'ambient', musicVolume: 55,
}
const initialDashboard: Dashboard = {
  account: { connected: false, username: 'silentforward', accountType: 'BUSINESS' },
  publishingReady: false,
  automation: { configured: false, lastRun: null },
  posts: [],
  settings: { autopilot: true, postTime: '09:00', reelTime: '19:00', timezone: 'Europe/Chisinau', queueDays: 14 },
  stats: { scheduled: 0, published: 0, failed: 0 },
  designOptions: fallbackOptions,
}

function tomorrowAt(hour = 9) {
  const date = new Date(Date.now() + 86_400_000)
  date.setHours(hour, 0, 0, 0)
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
}

function isoToLocalInput(value: string) {
  const date = new Date(value)
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
}

function initialDraft(): Draft {
  return {
    quote: 'Discipline is choosing what you want most over what you want now.',
    caption: 'Save this for the day you need it most.\n\nQuiet work. Visible results. Follow @silentforward for a daily reset.\n\n#motivation #discipline #mindset #selfimprovement #dailyquotes #growthmindset #consistency #focus #silentforward',
    accent: accents[0], format: 'post', scheduledFor: tomorrowAt(), design: { ...defaultDesign },
  }
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat('ro-RO', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
}

async function responseJson(response: Response) {
  const result = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(result.error || 'Cererea nu a putut fi finalizată.')
  return result
}

function Login({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function submit(event: FormEvent) {
    event.preventDefault()
    setLoading(true)
    setError('')
    try {
      await responseJson(await fetch('/api/auth/login', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }),
      }))
      onAuthenticated()
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Autentificarea a eșuat.')
    } finally {
      setLoading(false)
    }
  }

  return <main className="login-page">
    <section className="login-card">
      <div className="brand login-brand"><span>SF</span><strong>Silent Forward</strong></div>
      <p className="eyebrow">PRIVATE STUDIO</p>
      <h1>Conectează-te</h1>
      <p className="login-copy">Dashboardul, programarea și accesul la contul Instagram sunt protejate.</p>
      <form onSubmit={submit}>
        <label>Parolă<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus required /></label>
        <button className="primary" disabled={loading}>{loading ? 'Se verifică…' : 'Intră în studio'}</button>
        {error && <p className="form-notice error">{error}</p>}
      </form>
    </section>
  </main>
}

function DesignControls({ draft, options, onChange }: { draft: Draft; options: Dashboard['designOptions']; onChange: (draft: Draft) => void }) {
  const updateDesign = (values: Partial<Design>) => onChange({ ...draft, design: { ...draft.design, ...values } })
  return <div className="design-controls">
    <fieldset className="wide"><legend>Fundal</legend><div className="template-grid">
      {options.templates.map((template) => <button type="button" key={template} className={`template-chip theme-${template} ${draft.design.template === template ? 'selected' : ''}`} onClick={() => updateDesign({ template })}><span />{template}</button>)}
    </div></fieldset>
    <label>Font<select value={draft.design.font} onChange={(event) => updateDesign({ font: event.target.value })}>{options.fonts.map((font) => <option key={font} value={font}>{font}</option>)}</select></label>
    <label>Poziția textului<select value={draft.design.textPosition} onChange={(event) => updateDesign({ textPosition: event.target.value })}>{options.textPositions.map((position) => <option key={position} value={position}>{position}</option>)}</select></label>
    <label>Aliniere<select value={draft.design.textAlign} onChange={(event) => updateDesign({ textAlign: event.target.value })}>{options.textAlignments.map((align) => <option key={align} value={align}>{align}</option>)}</select></label>
    <label className="range-label">Dimensiune <output>{draft.design.fontSize}px</output><input type="range" min="48" max="112" step="2" value={draft.design.fontSize} onChange={(event) => updateDesign({ fontSize: Number(event.target.value) })} /></label>
    {draft.format === 'reel' && <>
      <label>Animație<select value={draft.design.animation} onChange={(event) => updateDesign({ animation: event.target.value })}>{options.animations.map((animation) => <option key={animation} value={animation}>{animation}</option>)}</select></label>
      <label className="range-label">Durată <output>{draft.design.duration}s</output><input type="range" min="6" max="15" value={draft.design.duration} onChange={(event) => updateDesign({ duration: Number(event.target.value) })} /></label>
      <label>Piesă<select value={draft.design.music} onChange={(event) => updateDesign({ music: event.target.value })}>{options.music.map((music) => <option key={music} value={music}>{music}</option>)}</select></label>
      <label className="range-label">Volum <output>{draft.design.musicVolume}%</output><input type="range" min="0" max="100" value={draft.design.musicVolume} onChange={(event) => updateDesign({ musicVolume: Number(event.target.value) })} /></label>
    </>}
  </div>
}

function VisualPreview({ draft }: { draft: Draft }) {
  const fontFamilies: Record<string, string> = { sans: 'Studio Sans', serif: 'Studio Serif', mono: 'Studio Mono' }
  return <div className={`post-preview ${draft.format} theme-${draft.design.template} position-${draft.design.textPosition}`}>
    <span className="preview-mark">SILENT FORWARD</span>
    <div className="preview-message" style={{ textAlign: draft.design.textAlign as 'left' | 'center' | 'right', fontFamily: fontFamilies[draft.design.font], fontSize: `${Math.max(17, draft.design.fontSize / 3)}px` }}>
      <p>{draft.quote}</p><span className={`accent-line align-${draft.design.textAlign}`} style={{ background: draft.accent }} />
    </div>
    <small>@silentforward</small>
  </div>
}

function DashboardApp({ onLogout }: { onLogout: () => void }) {
  const [data, setData] = useState<Dashboard>(initialDashboard)
  const [draft, setDraft] = useState<Draft>(initialDraft)
  const [saving, setSaving] = useState(false)
  const [notice, setNotice] = useState('')
  const [previewPost, setPreviewPost] = useState<Post | null>(null)
  const [previewLoading, setPreviewLoading] = useState(false)
  const [editing, setEditing] = useState<Post | null>(null)
  const [editDraft, setEditDraft] = useState<Draft | null>(null)
  const [filter, setFilter] = useState('all')

  async function refresh() {
    try {
      const response = await fetch('/api/dashboard')
      if (response.status === 401) return onLogout()
      setData(await responseJson(response))
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Serverul nu este disponibil.')
    }
  }

  useEffect(() => {
    refresh()
    const interval = window.setInterval(refresh, 30_000)
    return () => window.clearInterval(interval)
  }, [])

  const nextPost = useMemo(() => data.posts.find((post) => post.status === 'scheduled'), [data.posts])
  const visiblePosts = useMemo(() => data.posts.filter((post) => filter === 'all' || post.status === filter), [data.posts, filter])
  const automationHealthy = Boolean(data.automation.lastRun?.lastSuccessAt
    && Date.now() - new Date(data.automation.lastRun.lastSuccessAt).getTime() < 5 * 60_000)

  async function createPost(event: FormEvent) {
    event.preventDefault()
    setSaving(true)
    setNotice('')
    try {
      await responseJson(await fetch('/api/posts', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...draft, scheduledFor: new Date(draft.scheduledFor).toISOString() }),
      }))
      setNotice('Postarea a fost adăugată în program.')
      await refresh()
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Postarea nu a putut fi creată.')
    } finally {
      setSaving(false)
    }
  }

  async function randomize() {
    const quoteResponse = await fetch('/api/quotes/random')
    const quotes = await responseJson(quoteResponse)
    const pick = <T,>(values: T[]) => values[Math.floor(Math.random() * values.length)]
    setDraft((current) => ({
      ...current,
      quote: quotes[0],
      accent: pick(accents),
      design: {
        ...current.design,
        template: pick(data.designOptions.templates), font: pick(data.designOptions.fonts),
        textPosition: pick(data.designOptions.textPositions), textAlign: pick(data.designOptions.textAlignments),
        fontSize: 56 + Math.floor(Math.random() * 7) * 8,
        animation: pick(data.designOptions.animations), music: pick(data.designOptions.music), duration: 7 + Math.floor(Math.random() * 5),
      },
    }))
  }

  async function updateSettings(values: Partial<Dashboard['settings']>) {
    setData((current) => ({ ...current, settings: { ...current.settings, ...values } }))
    try {
      await responseJson(await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }))
      await refresh()
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Setările nu au putut fi salvate.')
    }
  }

  async function action(url: string, method = 'POST', success = 'Gata.') {
    setNotice('Se procesează…')
    try {
      await responseJson(await fetch(url, { method }))
      setNotice(success)
      await refresh()
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Acțiunea a eșuat.')
    }
  }

  async function removePost(post: Post) {
    if (!window.confirm(`Ștergi postarea programată „${post.quote}”?`)) return
    const response = await fetch(`/api/posts/${post.id}`, { method: 'DELETE' })
    if (!response.ok) {
      const result = await response.json().catch(() => ({}))
      return setNotice(result.error || 'Postarea nu a putut fi ștearsă.')
    }
    setNotice('Postarea a fost ștearsă din program.')
    await refresh()
  }

  async function openPreview(id: string) {
    setPreviewLoading(true)
    setPreviewPost(null)
    try {
      const post = await responseJson(await fetch(`/api/posts/${id}/preview`, { method: 'POST' }))
      setPreviewPost(post)
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Previzualizarea nu a putut fi generată.')
    } finally {
      setPreviewLoading(false)
    }
  }

  function openEditor(post: Post) {
    setEditing(post)
    setEditDraft({ quote: post.quote, caption: post.caption, accent: post.accent, format: post.format, scheduledFor: isoToLocalInput(post.scheduledFor), design: { ...post.design } })
  }

  async function saveEdit(event: FormEvent) {
    event.preventDefault()
    if (!editing || !editDraft) return
    setSaving(true)
    try {
      await responseJson(await fetch(`/api/posts/${editing.id}`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...editDraft, scheduledFor: new Date(editDraft.scheduledFor).toISOString() }),
      }))
      setEditing(null)
      setEditDraft(null)
      setNotice('Modificările și noua dată au fost salvate.')
      await refresh()
    } catch (reason) {
      setNotice(reason instanceof Error ? reason.message : 'Modificările nu au putut fi salvate.')
    } finally {
      setSaving(false)
    }
  }

  async function logout() {
    await fetch('/api/auth/logout', { method: 'POST' })
    onLogout()
  }

  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><span>SF</span><strong>Silent Forward</strong></div>
      <nav><a className="active" href="#overview">Overview</a><a href="#studio">Content studio</a><a href="#schedule">Program</a></nav>
      <div className="account-card"><span className={`dot ${data.account.connected ? 'online' : ''}`} /><div><strong>@{data.account.username}</strong><small>{data.account.accountType}</small></div></div>
      <button className="logout" onClick={logout}>Ieșire</button>
    </aside>
    <main className="dashboard-main">
      <header>
        <div><p className="eyebrow">CONTENT OPERATIONS</p><h1>Keep moving forward.</h1></div>
        <div className="header-actions">
          <div className="schedule-times"><label>Postare<input type="time" value={data.settings.postTime} onChange={(event) => updateSettings({ postTime: event.target.value })} /></label><label>Reel<input type="time" value={data.settings.reelTime} onChange={(event) => updateSettings({ reelTime: event.target.value })} /></label></div>
          <label className="switch-row"><span><strong>Autopilot</strong><small>1 postare + 1 Reel zilnic</small></span><input type="checkbox" checked={data.settings.autopilot} onChange={(event) => updateSettings({ autopilot: event.target.checked })} /></label>
        </div>
      </header>
      {!data.publishingReady && <section className="notice-card danger"><strong>Publicarea remote nu este configurată complet.</strong><p>Verifică variabilele Instagram și Cloudinary.</p></section>}
      {!data.automation.configured && <section className="notice-card danger"><strong>Programatorul Supabase nu este conectat la Vercel.</strong><p>Lipsește secretul comun al workerului remote.</p></section>}
      {data.automation.configured && <section className={`notice-card ${automationHealthy ? '' : 'danger'}`}>
        <strong>{automationHealthy ? 'Automatizarea remote este online.' : 'Automatizarea remote nu a raportat recent.'}</strong>
        <p>{data.automation.lastRun?.lastSuccessAt
          ? `Ultima verificare reușită: ${formatDate(data.automation.lastRun.lastSuccessAt)}.`
          : 'Așteptăm prima execuție a programatorului Supabase.'}
          {data.automation.lastRun?.lastError ? ` Ultima eroare: ${data.automation.lastRun.lastError}` : ''}</p>
      </section>}
      {notice && <section className="global-notice"><span>{notice}</span><button onClick={() => setNotice('')}>×</button></section>}
      <section id="overview" className="metrics">
        <article><span>Programate</span><strong>{data.stats.scheduled}</strong><small>în coada remote</small></article>
        <article><span>Publicate</span><strong>{data.stats.published}</strong><small>total postări</small></article>
        <article><span>Erori</span><strong>{data.stats.failed}</strong><small>necesită atenție</small></article>
        <article><span>Următoarea</span><strong className="metric-time">{nextPost ? formatDate(nextPost.scheduledFor) : '—'}</strong><small>{nextPost?.format === 'reel' ? 'Reel' : 'Postare'}</small></article>
      </section>
      <section id="studio" className="studio-grid">
        <div className="panel composer">
          <div className="section-heading"><div><p className="eyebrow">CREATE</p><h2>Content studio</h2></div><div className="heading-actions"><button type="button" className="secondary" onClick={randomize}>Surprinde-mă</button><span className="badge">Remote</span></div></div>
          <form onSubmit={createPost}>
            <label>Mesaj<textarea value={draft.quote} onChange={(event) => setDraft({ ...draft, quote: event.target.value })} maxLength={220} required /></label>
            <label>Descriere<textarea className="caption" value={draft.caption} onChange={(event) => setDraft({ ...draft, caption: event.target.value })} maxLength={2200} /></label>
            <div className="form-row">
              <fieldset><legend>Culoare accent</legend><div className="colors">{accents.map((color) => <button type="button" key={color} aria-label={`Alege ${color}`} className={draft.accent === color ? 'selected' : ''} style={{ background: color }} onClick={() => setDraft({ ...draft, accent: color })} />)}</div></fieldset>
              <label>Format<select value={draft.format} onChange={(event) => setDraft({ ...draft, format: event.target.value as Format })}><option value="post">Postare 4:5</option><option value="reel">Reel 9:16</option></select></label>
            </div>
            <DesignControls draft={draft} options={data.designOptions} onChange={setDraft} />
            <label>Data și ora acestei postări<input type="datetime-local" value={draft.scheduledFor} onChange={(event) => setDraft({ ...draft, scheduledFor: event.target.value })} required /></label>
            <button className="primary" disabled={saving}>{saving ? 'Se salvează…' : 'Programează postarea'}</button>
          </form>
        </div>
        <div className="preview-column"><VisualPreview draft={draft} /><p className="preview-label">Previzualizare • {draft.format === 'reel' ? '1080 × 1920' : '1080 × 1350'}</p></div>
      </section>
      <section id="schedule" className="panel queue">
        <div className="section-heading"><div><p className="eyebrow">QUEUE</p><h2>Program remote</h2></div><div className="heading-actions"><select className="filter" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Toate</option><option value="scheduled">Programate</option><option value="published">Publicate</option><option value="failed">Erori</option></select><span className="badge">{visiblePosts.length} postări</span></div></div>
        <div className="table-wrap"><table><thead><tr><th>Conținut</th><th>Design</th><th>Programare</th><th>Status</th><th /></tr></thead><tbody>
          {visiblePosts.map((post) => <tr key={post.id}><td><span className="mini-accent" style={{ background: post.accent }} /><strong>{post.quote}</strong>{post.error && <small className="row-error">{post.error}</small>}</td><td><span className="design-summary">{post.format === 'reel' ? 'Reel' : 'Post'} · {post.design.template}</span></td><td>{formatDate(post.scheduledFor)}</td><td><span className={`status ${post.status}`}>{post.status}</span></td><td><div className="row-actions"><button className="text-button muted" onClick={() => openPreview(post.id)}>Preview</button>{['scheduled', 'failed'].includes(post.status) && <><button className="text-button muted" onClick={() => openEditor(post)}>Editează</button><button className="text-button" onClick={() => action(`/api/posts/${post.id}/publish`, 'POST', 'Postarea a fost publicată.')}>Publică</button><button className="text-button muted" onClick={() => removePost(post)}>Șterge</button></>}<button className="text-button muted" onClick={() => action(`/api/posts/${post.id}/duplicate`, 'POST', 'Copia a fost adăugată mâine.')}>Duplică</button></div></td></tr>)}
          {!visiblePosts.length && <tr><td colSpan={5} className="empty">Nu există postări pentru acest filtru.</td></tr>}
        </tbody></table></div>
      </section>
    </main>
    {(previewLoading || previewPost) && <div className="modal-backdrop" role="presentation" onMouseDown={() => !previewLoading && setPreviewPost(null)}><section className="preview-modal" role="dialog" aria-modal="true" aria-label="Previzualizare postare" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Închide" onClick={() => setPreviewPost(null)}>×</button>{previewLoading ? <div className="preview-loading">Se generează randarea exactă…</div> : previewPost && <><div className="media-frame">{previewPost.format === 'reel' ? <video src={previewPost.mediaUrl} controls autoPlay loop /> : <img src={previewPost.mediaUrl} alt={previewPost.quote} />}</div><div className="preview-copy"><span className="badge">{previewPost.format === 'reel' ? `${previewPost.design.animation} · ${previewPost.design.duration}s · ${previewPost.design.music}` : `Postare · ${previewPost.design.template}`}</span><h2>{previewPost.quote}</h2><p>{previewPost.caption}</p></div></>}</section></div>}
    {editing && editDraft && <div className="modal-backdrop" role="presentation" onMouseDown={() => setEditing(null)}><section className="edit-modal" role="dialog" aria-modal="true" aria-label="Editează postarea" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Închide" onClick={() => setEditing(null)}>×</button><div className="section-heading"><div><p className="eyebrow">EDIT</p><h2>Postare programată</h2></div></div><form onSubmit={saveEdit}><label>Mesaj<textarea value={editDraft.quote} onChange={(event) => setEditDraft({ ...editDraft, quote: event.target.value })} maxLength={220} required /></label><label>Descriere<textarea className="caption" value={editDraft.caption} onChange={(event) => setEditDraft({ ...editDraft, caption: event.target.value })} /></label><div className="form-row"><label>Format<select value={editDraft.format} onChange={(event) => setEditDraft({ ...editDraft, format: event.target.value as Format })}><option value="post">Postare 4:5</option><option value="reel">Reel 9:16</option></select></label><label>Data și ora<input type="datetime-local" value={editDraft.scheduledFor} onChange={(event) => setEditDraft({ ...editDraft, scheduledFor: event.target.value })} /></label></div><DesignControls draft={editDraft} options={data.designOptions} onChange={setEditDraft} /><button className="primary" disabled={saving}>{saving ? 'Se salvează…' : 'Salvează modificările'}</button></form></section></div>}
  </div>
}

function App() {
  const [session, setSession] = useState<'loading' | 'authenticated' | 'anonymous'>('loading')
  useEffect(() => {
    fetch('/api/auth/session').then((response) => response.json()).then((result) => setSession(result.authenticated ? 'authenticated' : 'anonymous')).catch(() => setSession('anonymous'))
  }, [])
  if (session === 'loading') return <main className="splash"><div className="brand"><span>SF</span><strong>Silent Forward</strong></div></main>
  if (session === 'anonymous') return <Login onAuthenticated={() => setSession('authenticated')} />
  return <DashboardApp onLogout={() => setSession('anonymous')} />
}

export default App
